modules/Bio/EnsEMBL/VEP/Runner.pm, t/Runner.t
The plugins key could be created somewhere else but without defined value. This
could cause issue if the plugins list is later de-referenced.
This fix needs to go into release/87 too.
=> Use "defined" to test if there is a plugins list

modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/Transcript.pm
For VectorBase and Ensembl Genomes, the meta key 'initial_release_date' is often missing, and does not reliably indicate the geneset version if it does exist. The most useful key for this is 'genebuild.version'; since this is never used in Ensembl, if it exists it can overwrite 'initial_release_date' for EG, but otherwise the behavior of the module is unchanged.
=> Adding genebuild version for non-vertebrates to info.txt file

modules/Bio/EnsEMBL/VEP/Constants.pm
Dear Ensembl Developers,
the linked commit fixes the vep --flag_pick_allele_gene option that did not yield a PICK field in the (VCF) output.
Thanks, Michael
=> Fix for vep option --flag_pick_allele_gene

modules/Bio/EnsEMBL/VEP/InputBuffer.pm, modules/Bio/EnsEMBL/VEP/OutputFactory.pm, modules/Bio/EnsEMBL/VEP/Parser.pm, t/InputBuffer.t, t/Parser.t, t/Parser_HGVS.t, t/Parser_ID.t, t/Parser_VCF.t, t/Parser_VEP_input.t
Historically VEP has used $vf->{start} for coordinate lookup, and
mostly it works fine. Some of the TranscriptMapper methods
require $vf->seq_region_start(). Mostly this is OK as it just does
a slice-based lookup, but for circular slices e.g. in E.coli the
core API tries to do a DB lookup based on $vf->dbID, which
of course fails.
We get around it by caching seq_region_start on the VF itself.
This depends on an update the ensembl-variation
BaseVariationFeature module to implement that caching and avoid
defaulting to the parent method in Feature.
Have to be careful though, particularly when split_variants() and
minimise_alleles() create copies of VFs, hence the changes there.
=> Use cached seq_region_start and seq_region_end

modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm, modules/Bio/EnsEMBL/VEP/OutputFactory.pm, modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm, t/OutputFactory.t, t/Runner.t, vep
This flag will add version number to transcript IDs in the output file. Note it won't add them to RefSeq identifiers, as they already have the version number in the `$tr->stable_id` property. This may change in future, so something to be aware of.
This PR also includes a couple of minor unrelated fixes.
=> Add support for --transcript_version

filter_vep, modules/Bio/EnsEMBL/VEP/OutputFactory.pm, t/Runner.t
filter_vep will now by default parse VEP annotations encoded in the CSQ
INFO field of a VCF; this can be configured (e.g. to use ANN) with
--vcf_info_field.
Addresses https://github.com/Ensembl/ensembl-vep/issues/108
=> Refine filter_vep handling of VCF

modules/Bio/EnsEMBL/VEP/Constants.pm, modules/Bio/EnsEMBL/VEP/OutputFactory/JSON.pm, modules/Bio/EnsEMBL/VEP/Parser/VEP_input.pm
- fix for gene symbol "NANS" becoming numeric entity NaN (not a number) under newer perls on Windows
- fix for carriage returns sneaking into parsed fields in VEP input format
=> minor fixes

modules/Bio/EnsEMBL/VEP/Parser/HGVS.pm
Prevents whole exception messages being printed to screen with common errors
Other messages can be added to the known_messages array to remove those exception messages also.
=> Handled length exception more cleanly

modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/DumpVEP_conf.pm
The file has been updated with newly generated 1000 Genomes phase 3 data which addressed mapping issues where alleles haven't been correctly reverse complemented. This will fix [ENSVAR-988](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-988)
Production will run dumps from release branch.
=> update 1KG data file

filter_vep
Fix warning that argument to throw was not numeric
Bio::EnsEMBL::Utils::Exception::throw
Arg [1] : string $msg
Arg [2] : (optional) int $level
=> Fix throw argument for existing output file

filter_vep
Splitting the CSQ in VCF did not take into account trailing empty fields.
When no matches were found with the --count option, an empty line was returned. Now returns 0
=> Include trailing empty fields in CSQ and report 0 matches

docker/Dockerfile
We use VEP in an HPC cluster that doesn't support docker. We use [singularity](http://singularity.lbl.gov/) instead, which supports running docker images. Currently, we have some issues with the conversion from the docker images, because of the following definitions in the Dockerfile:
1) The locales are no set properly.
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
LANGUAGE = (unset),
LC_ALL = (unset),
LC_COLLATE = "C",
LANG = "en_US.UTF-8"
are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```
2) In singularity $HOME is inherited from the host, so we need some cumbersome settings to run the containers in other folder. And the Dockerfile is installing everything in `/home`.
In this PR, I …
=> Improve Dockerfile: configure locales and a proper /opt installation dir

modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/QCDump.pm
The QC step was failing because during a VEP run errors like _No sequence found for seq_region 13699:62522_ occurred. At the same time we would get warnings: _WARN: Species (homo_sapiens) and group (core) same for two separate databases_ There could have been a conflict between different core databases (core and otherfeature maybe). Calling clear on the registry is solving the problem. Although, I don't know exactly why.
=> Clear registry before running VEP

modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm, t/Haplo_AnnotationSource_File_GFF.t
Fix for #210 - some CDS lines are currently skipped, so exons are missinterpreted as UTR and start codons wrongly placed.
=> fix for missing CDS in custom GFF

modules/Bio/EnsEMBL/VEP/Parser/HGVS.pm
PR to filter out user-given HGVS that includes square brackets - causing issues on web
As #276 but with a cleaner commit history
=> Ignore HGVS input that include square brackets

modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/RegFeat.pm, modules/Bio/EnsEMBL/VEP/Constants.pm
This fix will ignore empty MotifFeatures. For release/96 we are more carful with dumping regulatory data into cache files and won't have to deal with reading empty MotifFeatures from cache files.
=> ignore empty motifFeatures

modules/Bio/EnsEMBL/VEP/Config.pm, modules/Bio/EnsEMBL/VEP/Constants.pm, modules/Bio/EnsEMBL/VEP/InputBuffer.pm, modules/Bio/EnsEMBL/VEP/Parser/VCF.pm, t/Haplo_Runner.t, t/OutputFactory_VCF.t, t/Parser_VCF.t, vep
Complex SV cannot currently be annotated, so skip them. 
Long SV require large amounts of memory, so a default max size is set which can be overridden on the command line.
Docs to follow
=> skip long and complex SV and enable overlaps in VCF

modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm
The test was failing on the Docker build as the tree is now composed of 2 chromosomes (21 and 22) and for some reason, the tests on Docker built them in the order `22->21` whereas Travis built it in the order `21->22`.
=> Keep same chromosome ordering for the transcript tree

modules/Bio/EnsEMBL/VEP/Parser/VCF.pm, t/Parser_VCF.t
Previously the SO type was derived from the ALT allele - this doesn't work for CNVs with alleles "CN0", "CN0,CN2,CN3" and "CN2" - now use SVTYPE: DEL, CNV, DUP respectively first for CNVs
=>  use SVTYPE to define type in preference to ALTs for CNVs 

INSTALL.pl
Linked to https://github.com/Ensembl/ensembl-vep/pull/536
Updates the versions of HTSLib and Bio::DB::HTS within the VEP installer. New dependancies are introduced that the installer asks the user to add.
A discussion needs to be had within the team of the best way to resolve these dependancies across multiple operating systems.
=> HTSLib & Bio::DB::HTS updates within installer

modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/Dumper/Variation.pm
Prevents the issues we had in 97 with the GRCh37 all_vars.gz files being empty after dumping
=> Add buffer_size check to sort command in dumping pipeline

modules/Bio/EnsEMBL/VEP/Parser/VCF.pm, t/Parser_VCF.t
We don't currently handle break ends as fusions. The second break point is treated as if it is the end of a contiguous feature, which is very missleading when different chromosomes are involved. 
This does not provide full BND support, but does set the SV end to be the same as start when different chromosomes are involved, so only the features at the 'ref' break are reported.  
As discussed in: https://github.com/Ensembl/VEP_plugins/pull/232
Also sets class to BND.
=> Set breakend end position to be the start position

modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm, t/OutputFactory_VCF.t
This is linked #602. When --sift s option is used, 0 SIFT values are not in VCF output.
=> Keep zero values in VCF

modules/Bio/EnsEMBL/VEP/Constants.pm, modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm, t/OutputFactory_VCF.t
This is the same as #604 on branch release/97. 
Fix for when --sift s option is used, 0 SIFT values are not in VCF output.
=> Keep zero values in VCF - 97

modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm, t/OutputFactory_VCF.t
This is the same as #604 on branch postreleasefix/99
Fix for when --sift s option is used, 0 SIFT values are not in VCF output.
=> Keep zero values in VCF - 99

t/Parser_VCF.t
Remove the warning message when running the test `t/Parser_VCF.t`:
```
"my" variable $cnv_vf masks earlier declaration in same scope at ./t/Parser_VCF.t line 570.
```
=> Remove warning 'variable my  masks earlier declaration'

filter_vep
#580 (ENSVAR-2602)
INFO and CSQ fields were being loaded for each feature overlaping a variant.
=> Improve filter_vep memory usage

modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/Dumper/Core.pm
Designed to solve the issue:
_Can't store CODE items at Storable.pm line 303, at ensembl-vep/modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/Dumper.pm line 167._
Some bacteria dumps (e.g. _chlamydia_trachomatis_gca_000590735_) have database adaptors attached to the transcript slices. Not sure why. This removes them all before dumping.
I've redumped human with this change. Output is the same, doesn't cause a slowdown.
=> Remove all adaptors from core dump

INSTALL.pl
As described in https://github.com/Ensembl/ensembl-vep/issues/610, the CONVERT flag no longer works after changing the installer to download the indexed cache files by default
Incase there are users who want to convert old cache files, I've restored this functionality for when the --CONVERT flag is used.
=> Allow installer to convert cache if requested

INSTALL.pl
We used to remove lines from Bio::DB::HTS' BUILD.PL and create a new Build.PL.new, however this is no longer needed.
=> Remove build.pl patch

modules/Bio/EnsEMBL/VEP/Parser/HGVS.pm
Giving the input `NM_001258273.1:c.1A>T,` to variant recoder was returning odd results, including `NM_001258273.1:c.-632A>T`
Variant recoder was generating a $vf object using a transcript generated by calling $ta->fetch_all_by_external_name on the core db, which was not an exact match. The change skips the core database and looks directly in otherfeatures for transcripts that look like RefSeq transcripts.
=> Prevent looking up of NM/XMs in core db

modules/Bio/EnsEMBL/VEP/FilterSet.pm, t/FilterSet.t
Currently, filter_vep doesn't filter values '0.7&0.5' or '0.7,0.5'. 
This fix splits the values and checks them individually.
=> Filter vep - allow filtering multiple values

modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/Transcript.pm, modules/Bio/EnsEMBL/VEP/Parser/HGVS.pm
No test has been added as we don't have a 37 test database.
This should remove both refseq_import and refseq_human_import transcripts.
=> Remove old 37 transcripts from VEP (and cache files)

modules/Bio/EnsEMBL/VEP/Runner.pm, t/Runner.t
Currently it requires both flags, which is unnecessary.
I'll submit a PR to postreleasefix/101 when this is approved
=> Turn on shift_3prime when shift_genomic is switched on 

modules/Bio/EnsEMBL/VEP/Constants.pm, modules/Bio/EnsEMBL/VEP/OutputFactory/JSON.pm, modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm, t/OutputFactory_JSON.t
Reset_shifted_positions method was only called in the primary OutputFactory.pm - needs to be called within JSON & VCF output factories too
=> Reset shifted positions correctly for VCF and JSON output

modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/Dumper/Regulation.pm
The feature_type value for regulatory features was missing - caused by changes in the funcgen api for 100.
=> Check so_term if so_name is empty

t/Parser.t
Core has updated the mapper code to deal with transforming insert features to toplevel.
=> test contig to toplevel for insertion

modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/DumpVEP_conf.pm
At the moment strains and breeds are not shown in the list of species on VEP tools. We already dump dog and pig breeds and we want to show the new sheep reference and the previous sheep reference which has a widely used variation database.
In order to make it easier for the web code to show all strains and breeds and not make exceptions for mouse we will also dump the mouse strains from release 102.
=> include mouse strains

modules/Bio/EnsEMBL/VEP/VariantRecoder.pm, t/VariantRecoder.t
Variant Recoder output to be specific by allele. 
COSMIC and HGMD ids are not linked to any allele - in the output, these ids are displayed for all alleles. 
Example to test: rs1160446270
=> Change Variant Recoder output structure

modules/Bio/EnsEMBL/VEP/OutputFactory/JSON.pm, t/OutputFactory_JSON.t
This is related to  #938. For further details and examples see: ENSVAR-4006
=> VEP JSON output - remove frequencies of non-matching co-located alleles

modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/DumpVEP_conf.pm
We used r2.1 before and it is better to use r2.1.1 for consistency.
=> use r2.1.1 for consistency

modules/Bio/EnsEMBL/VEP/Stats.pm
A hyphen in a chromosome name which is used for creating the javascript variable name was breaking the html display. Hyphens are not allowed in javacscript names. My script for reproducing and testing can be found here PANDA/anja/vep_issue_974.
Issue was reported here #974
=> replace dash in var name

modules/Bio/EnsEMBL/VEP/Config.pm, modules/Bio/EnsEMBL/VEP/Runner.pm
Providing a different port number for GRCh37 databases was ignored because of small bug in the condition statement.
This was reported here https://github.com/Ensembl/ensembl-vep/issues/958
It can be tested with our GRCh37 mirror server.
=> fix condition for setting grch37 port

modules/Bio/EnsEMBL/VEP/OutputFactory.pm
To prevent random ordering of fields in the case where there are multiple subpopulations with the same maximum frequency
=> Sort order of processing of frequency keys

modules/Bio/EnsEMBL/VEP/Config.pm, modules/Bio/EnsEMBL/VEP/Constants.pm, modules/Bio/EnsEMBL/VEP/OutputFactory.pm, modules/Bio/EnsEMBL/VEP/OutputFactory/JSON.pm, modules/Bio/EnsEMBL/VEP/VariantRecoder.pm, t/Runner.t, t/VariantRecoder.t, variant_recoder, vep
Adds option to output GA4GH VRS Allele object in Variant Recoder and VEP
For further info see: 
ENSVAR-4092 Variant Recoder
ENSVAR-4186 VEP
Requires https://github.com/Ensembl/ensembl-variation/pull/739
=> GA4GH VRS Allele object to variant recoder

modules/Bio/EnsEMBL/VEP/OutputFactory/JSON.pm, modules/Bio/EnsEMBL/VEP/OutputFactory/VEP_output.pm, t/OutputFactory_JSON.t
'used_ref' and 'given_ref' are missing from JSON output when the value is '-'
More details: ENSVAR-4492
=> Include missing values in JSON output

INSTALL.pl
This hopefully fixes an issue where a failure during archive extraction will be silent. The expected behaviour is that INSTALL.pl will stop with a nonzero exit code if unzip/tar/gzip fails.
NB: I've not tested this.
=> system and die, not backticks and die

.github/workflows/merge-branches.yml
After merging a PR targeting a branch named **postreleasefix/XX** and containing the label `auto-merge`, this GitHub Actions script will merge branch **posteleasefix/XX** with branch **release/XX** and **master** (the script takes 30 seconds to run).
* PR contains `auto-merge` label
* PR targeting a branch whose name starts with `postreleasefix/`
* The script is only triggered after the PR is merged
If these conditions are not met, the branches will not automatically merge when merging the PR. However, the changes will be automatically merged in later PRs that meet the previous conditions.
After merging a PR labelled `auto-merge` and targeting `postreleasefix/107`, this script will be triggered:
1. Get the release version based on the last digits of the branch: `107`
2. Merge …
=> Automatically merge postreleasefix branch with release and master

modules/Bio/EnsEMBL/VEP/Constants.pm, t/test-genome-DBs/homo_vepiens/core/table.sql, t/test-genome-DBs/homo_vepiens/funcgen/table.sql, t/test-genome-DBs/homo_vepiens/otherfeatures/table.sql, t/test-genome-DBs/homo_vepiens/variation/table.sql, t/test-genome-DBs/homo_vepiens_coreonly/core/table.sql, t/test-genome-DBs/multi/ontology/table.sql, t/test-genome-DBs/mus_muscuvep/core/meta.txt, t/test-genome-DBs/mus_muscuvep/core/table.sql
Based on issue #1153
Running `prove -v t/*.t` returns no errors after these changes.
=> Discard references to 107 in release 106

modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/Dumper/Variation.pm
Die if temp_dir creation fails. In some cases, temp_dir creation may fail, for example, in case it needs to be created recursively. We currently made it mandatory pre-requisite to create temp_dir before running pipeline instead of handling it on the code -
https://www.ebi.ac.uk/seqdb/confluence/display/EV/VEP+dumps#VEPdumps-Pre-requisites
JIRA - https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4860
=> Creating temp_dir before running pipeline should be mandatory

modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/QCDump.pm
Solves [ENSVAR-4737](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4737) problem for the MT region of _Macaca mulatta_.
After dumping the VEP cache, [QCDump.pm](https://github.com/Ensembl/ensembl-vep/blob/master/modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/QCDump.pm) checks if the cache directory names exist as sequence region names reported from the **otherfeatures** database. However, this fails if the directory cache exists only in the **core database** but not in **otherfeatures**. The quality control check should gracefully handle such cases.
This PR brings the following enhancement: in case of failing the check because the directory does not exist in **otherfeatures**, check all available sequence regions using **seqlevel** (that lists all sequence regions names) instead of …
=> Fix QCDump failing for regions not available in otherfeatures

modules/Bio/EnsEMBL/VEP/CacheDir.pm, t/CacheDir.t
Jira: [Card](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4861)
An user (https://github.com/Ensembl/ensembl-vep/issues/1180) was successfully able to  run `vep --species homo_sapiens_refseq` without getting any error. This behavior created a bad annotated VCF as a result.
This PR was created to not allow users using specifically `--species homo_sapiens_merged` or `--species homo_sapiens_refseq`.
1) Try using vep with and without `--species homo_sapiens_refseq` and see if it errors pop out.
=> refactor: bad --species homo_sapiens usage

modules/Bio/EnsEMBL/VEP/AnnotationSource/File/GFF.pm
[ENSVAR-4310](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4310): for the new Ensembl GFF format, we may rename the current **biotype** attribute as **transcript_biotype**. This PR allows to support that potential change.
Also resolves #868 that asks to support this attribute in GFFs for consistency with GTF  file parsing. This way, parsing both GTF and GFF files will allow us to get transcript biotypes based on one of these attributes: **biotype**, **transcript_type** or **transcript_biotype**.
(Should I include a unit test for this change?)
Input:
-  [Sample GFF input.zip](https://github.com/Ensembl/ensembl-vep/files/8532618/Sample.GFF.input.zip): two Tabix-indexed human annotations for chromosomes 21 and 22. One of the annotations has biotype attributes named as `biotype` and the …
=> Get biotype from GFF's transcript_biotype attribute

modules/Bio/EnsEMBL/VEP/AnnotationSource/File/GFF.pm
[ENSVAR-5020](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5020)
```
zcat t/testdata/custom/refseq.gff.gz \
| sed 's/\tgene\t/\tprotein_coding_gene\t/; s/NC_000021.9/21/' \
| bgzip > ../refseq2.gff.gz
tabix ../refseq2.gff.gz
```
```
vep --force_overwrite -i t/testdata/input/test.vcf --gff ../refseq2.gff.gz --fasta t/testdata/fasta/Homo_sapiens.GRCh38.toplevel.test.fa 
WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: gene49534, gene49532, gene49521, gene49527, gene49525, gene49522, gene49524, gene49518, gene49523, gene49537, gene49535, gene49531, gene49516, gene49536, gene49519, gene49514, gene49528, gene49513, gene49526
```
No warnings and VEP assigns consequences other than intergenic
=> Include protein_coding_gene in the GFF inclusion list

modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm
[ENSVAR-5034](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5034)
This PR aims to warn users when unsupported feature_types are present in the GFF file.
```
zcat t/testdata/custom/refseq.gff.gz \
| sed 's/\tgene\t/\tncRNA_gene\t/; s/NC_000021.9/21/' \
| bgzip > ../refseq2.gff.gz
tabix ../refseq2.gff.gz
```
```
vep --force_overwrite -i t/testdata/input/test.vcf --gff ../refseq2.gff.gz --fasta t/testdata/fasta/Homo_sapiens.GRCh38.toplevel.test.fa
```
```
WARNING: The feature_type region is being skipped
WARNING: The feature_type match is being skipped
WARNING: The feature_type ncRNA_gene is being skipped
WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: gene49536, gene49532, gene49523, gene49518, gene49535, gene49516, gene49526, gene49528, …
```
=> Issue warnings to notify unsupported feature_types

modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/RegFeat.pm
JIRA: [Card](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5135)
While running last VEP Dump this bug was found:
```sh
Can't use an undefined value as an ARRAY reference at /hps/software/users/ensembl/repositories/enseven/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/RegFeat.pm line 224.
```
1) Just need to make sure that Vep Dump it's working with new function for RegFeat.pm
=> fix: use of get_all_overlapping_Peaks method

INSTALL.pl, modules/Bio/EnsEMBL/VEP/Config.pm
[ENSVAR-5187](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5187)
This PR allows VEP and `INSTALL.pl` to accept any env vars prefixed with `VEP_` as arguments (useful for future improvements to VEP Docker image). For example, in place of `vep -i input.vcf --dir_plugins /vep/plugins`, we may use:
```
export VEP_DIR_PLUGINS=/vep/plugins
vep -i input.vcf
```
The value of `VEP_DIR_PLUGINS` is ignored if we define `--dir_plugins` in the command line or in INI configuration files.
Similarly to function [read_config_from_file()](https://github.com/Ensembl/ensembl-vep/blob/02c81df4cd174ce15273dea87d39337d79ce5df7/modules/Bio/EnsEMBL/VEP/Config.pm#L732-L783), all env vars prefixed with `VEP_` and their values are stored in the `$config` hash variable.
- Improve introductory message to mention all …
=> Support environment variables as arguments for VEP and INSTALL.pl

INSTALL.pl
This PR updates all ftp URLs from `http://` and `ftp://` protocol to https.
The affected hostnames have been tested to work with https.
Other affected repos are listed in the JIRA ticket.
Webteam JIRA ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6632
Sandbox: http://wp-np2-1d.ebi.ac.uk:1680/
=> Update ftp links to https

modules/Bio/EnsEMBL/VEP/Config.pm
This hotfix allows running VEP using `--cache` without a value, e.g.: `vep -i variants.vcf --cache`.
=> Hotfix: accept cache argument without value

modules/Bio/EnsEMBL/VEP/Config.pm, t/Config.t, t/testdata/vep.ini
**Issue**
When given config file to VEP it parses the parameters by whitespace and = , but in our doc says the key value pair are whitespace seprated - https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_config 
Moreover splitting by = has problem with plugins like IntAct and SpliceAI as they have = in their args - 
```
plugin IntAct,mutation_file=/nfs/production/flicek/ensembl/variation/enseweb-data_tools/grch38/e108/vep/plugin_data/mutations.tsv,mapping_file=/nfs/production/flicek/ensembl/variation/enseweb-data_tools/grch38/e107/vep/plugin_data/mutation_gc_map.txt.gz,pmid=1
plugin SpliceAI,snv=/nfs/production/flicek/ensembl/variation/enseweb-data_tools/grch38/e108/vep/plugin_data/spliceai_scores.masked.snv.hg38.vcf.gz,indel=/nfs/production/flicek/ensembl/variation/ens …
```
=> Fix config file parsing

docker/Dockerfile
* [ENSVAR-4082](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4082) and #981
* Remove `.cpanm` cache for root (not required to run VEP)
* Reduces image size from 787MB to 665MB
* [ENSVAR-5183](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5183)
* Automatically skip update checks for VEP and Ensembl API when running `INSTALL.pl`
* [ENSVAR-5184](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5184)
* Change default working directory to `/data`
1. Build a Docker image with the Dockerfile from this PR, e.g., `docker build -t vep .` (replace `ENV BRANCH main` with `ENV BRANCH release/109` in the Dockerfile, otherwise you won't be able to test skipping of update checks when running `INSTALL.pl`)
2. Run `docker run -ti vep` and check if `pwd` is `/data`
3. When running simply the command …
=> Improve VEP Docker image

INSTALL.pl, modules/Bio/EnsEMBL/VEP/Constants.pm
Fixes #1284: `INSTALL.pl` cache/FASTA downloads are breaking in `release/108` because they expect FTP URLs but we have changed them for HTTPS links. This PR fixes those issues.
=> Hotfix INSTALL.pl URL downloads

INSTALL.pl, modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm, modules/Bio/EnsEMBL/VEP/OutputFactory.pm
Jira: [Card](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5028)
[StructuralVariationOverlap](https://github.com/Ensembl/VEP_plugins/blob/release/107/StructuralVariantOverlap.pm) plugin retrieves information from overlapping structural variants. Output should have percentage (PC) + allele frequency (AF) if exists. Using vep `--custom`, we can already retrieve AF information easily, but percentage will not be calculated. This PR is meant to add PC information by default into SV custom overlap usage.
1) Use `--custom` with and without `PC` as a field. For example:
```sh
vep ... --custom gnomad_chr22.vcf.gz,prefix,vcf,overlap,0,PC,info_columns
vep ... --custom gnomad_chr22.vcf.gz,prefix,vcf,overlap,0,info_columns
```
=> feat: Integrate SVO plugin to VEP - add PC field

INSTALL.pl
Based on [ENSVAR-4682](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4682):
- **New:** `--PLUGINS list` lists all available plugins
- **Fix:** `--PLUGINS all` should not print `WARNING: The following plugins have not been found: all`
Also:
- **New:** argument `--NO_PLUGINS` skips plugin installation step
- Useful for future VEP Docker image with plugins already installed
- **Fix:** when prompting the user for plugins, if the user inputs a value outside of the available plugins (e.g., `61`), warn the user that the selected plugin is not available
1. `perl INSTALL.pl -a p --PLUGINS list` should show a list of plugins
3. `perl INSTALL.pl -a p --PLUGINS all` should download all plugins without displaying the warning message `WARNING: The following plugins have not been found: all`
4. …
=> Improve plugin installation in `INSTALL.pl`

nextflow/README.md, nextflow/nf_config/nextflow.config, nextflow/nf_modules/merge_chros_VCF.nf, nextflow/nf_modules/read_chros_VCF.nf, nextflow/workflows/run_vep.nf
- New option `--output_prefix` to overwrite output file name
- Do not try to create index file if already present
- It has been always taking chromosomes from the `params.chros` - by default comment out the `param.chros` in config (reverted).
- The tabix index file is mandatorily generated, it is better to use `tabix` instead of `bcftools` to read chromosomes from the file because that will remove dependency from the header. So even if there is no proper header in the input vcf we will get the chromosomes.
=> Some re-factoring on nextflow vep

docker/Dockerfile
[ENSVAR-4574](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4574): Adding VEP plugins to docker image
* Plugins are installed to `/plugins`
* Dependencies are installed based on files from VEP_plugins repo: https://github.com/Ensembl/VEP_plugins/pull/553
To test this PR, first change the line starting with `ENV PLUGIN_DEPS` to my repo:
```
ENV PLUGIN_DEPS "https://raw.githubusercontent.com/nuno-agostinho/VEP_plugins/improve/vep-docker/config"
```
After using this Dockerfile to build a Docker image (e.g., named `vep-plugins`), you can run a plugin like this:
```
docker run -v $HOME/vep_data:/data vep-plugins vep \
--i input.vcf \
--database \
--plugin Blosum62
```
You can try using `--database` to avoid installing cache. If needed, you can install the cache in a folder such as …
=> Add plugins to VEP Docker image

t/OutputFactory_Tab.t, t/OutputFactory_VCF.t, t/OutputFactory_VEP_output.t
Tests are not passing due to `--species homo_sapiens` default was included on test.
1) Just wait for travis.
=> hotfix: Remove default `homo_sapiens` from header test

modules/Bio/EnsEMBL/VEP/Parser/VCF.pm
Jira: [Card](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5031)
Some structural variants does not have SVTYPE included on INFO field + follow specific pattern to determine if is a deletion, duplication or copy number variation. This PR includes does specific patterns and relate than to their SO terms.
1) Besides <CN=0> (DEL) or <CN=2> (DUP) or <CN=0>,<CN=2> (CNV) patterns, we might have lots of patterns for CNV as:
<CN=0>,<CN=1>,<CN=2>,<CN=3>,....,<CN=n>, as n = number of amount of copy numbers in that variant.
2) Sometimes <CN=0>, might be represented as <CN0>, as well as, other \<CN\>'s.
1) Run a VCF with all those cases and check if does it work, i.e:
```sh
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       713044  CNV     C       <CN=0>,<CN=2>   .       . …
```
=> feat: Add SO terms based on CN alterations

INSTALL.pl
Fix #1302:
* Fix download of cache and FASTA files for fallback cases.
* Allow user-provided links with `ftp://` protocol to download cache and FASTA.
=> Hotfix for FTP/HTTP links in `INSTALL.pl`

modules/Bio/EnsEMBL/VEP/Parser/VCF.pm
When SV are annotated by VEP, `Allele` column usually get a SO term class (insertion, deletion, duplication, etc) in VCF case.
This PR is meant to include missing SO term classes.
INV => inversion (http://www.sequenceontology.org/browser/current_release/term/SO:1000036)
BND => breakpoint (http://www.sequenceontology.org/browser/current_release/term/SO:0000699 - synonym)
1) Check if `Allele` column have a SO term in INV and breakpoint cases, ie.
```sh
INPUT:
2	127050429	INV_exon	N	<INV>	.	.	END=127050512
2	127050429	BND_exon	N	<BND>	.	.	END=127050512;CHR2=chr3;END2=127050512
BEFORE:
2       127050429       INV_exon        N       <INV>   .       .       END=127050512;CSQ=INV|...
2       127050429       BND_exon        N       <BND>   .       . …
```
=> refactor: Include SV SO terms

modules/Bio/EnsEMBL/VEP/Config.pm, modules/Bio/EnsEMBL/VEP/Constants.pm, modules/Bio/EnsEMBL/VEP/OutputFactory.pm, modules/Bio/EnsEMBL/VEP/OutputFactory/JSON.pm, modules/Bio/EnsEMBL/VEP/VariantRecoder.pm, t/Runner.t
[ENSVAR-5274](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5274): The [GA4GH Variation Representation Specification](https://vrs.ga4gh.org/) is a standard written in JSON. Previously, this flag was only compatible with JSON, but we need to support more output formats in order to enable support for `--ga4gh-vrs` in VEP and VR: https://github.com/Ensembl/ensembl-rest/pull/570
Unfortunately, the VCF format replaces the commas from this representation to `&`, so I made the flags `--vcf` and `--ga4gh-vrs` as incompatible.
- Run VEP with and without `--ga4gh_vrs` and check the following output formats:
- **JSON:** prints the `ga4gh_vrs` as normal JSON
- **VCF:** raises error message stating that VCF output is incompatible with `--ga4gh-vrs` flag
- **Other formats:** prints the `ga4gh_vrs` as …
=> Support `ga4gh-vrs` flag in all formats except VCF

modules/Bio/EnsEMBL/VEP/AnnotationSource.pm, modules/Bio/EnsEMBL/VEP/InputBuffer.pm, modules/Bio/EnsEMBL/VEP/OutputFactory/JSON.pm, modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm, modules/Bio/EnsEMBL/VEP/OutputFactory/VEP_output.pm
An user reported that still wants variants skipped by `--max_sv_size` to be included in output VCF (https://github.com/Ensembl/ensembl-vep/issues/600). This PR still skips annotation but include VCF line without any annotation.
1) Use `--max_sv_size` flag with SV variants. It should keep warning and keep variants, i.e:
INPUT:
```sh
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       121035  gnomAD  N       <DEL>   .       .       END=1121130;SVTYPE=DEL
1       95244265        95244265        A       C       .       .       .
```
BEFORE:
```sh
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       95244265        95244265        A       C       .       .       CSQ=C|missense_variant|MODERATE|RWDD3|ENSG00000122481|Transcript|ENST00000263893|protein_coding|2/3|| …
```
=> feat: Include not annotated skipped --max_sv_size

modules/Bio/EnsEMBL/VEP/Constants.pm
Before branching we need to update `Constants.pm` VEP version.
Last release example:
https://github.com/Ensembl/ensembl-vep/pull/1260
=> feat: Update Constants.pm version e110

vep
In the documentation, the option `shift_genomic` accepts a value (0 or 1) however running vep with `shift_genomic 1` throws an error:
`ERROR: Unexpected extra command-line parameter(s): 1 at /hps/software/users/ensembl/repositories/dlemos/ensembl-vep/vep line 220.`
=> Fix option shift_genomic

modules/Bio/EnsEMBL/VEP/Config.pm, modules/Bio/EnsEMBL/VEP/OutputFactory.pm
[ENSVAR-5409](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5409)
=> Updating changes for the pick option

t/OutputFactory.t
[ENSVAR-3733](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3733): change impact of `feature_elongation` from `MODIFIER` to `HIGH` in VEP unit tests
Only merge for e110 (requires documentation updates: https://github.com/Ensembl/public-plugins/pull/643).
Expect Travis-CI to fail until https://github.com/Ensembl/ensembl-variation/pull/928 is merged
=> Update impact of `feature_elongation` consequences (e110)

INSTALL.pl, modules/Bio/EnsEMBL/VEP/Constants.pm
Fixes #1354: error thrown when setting the environment variable `VEP_VERSION` with something other than the major version of VEP, given that the script tries to fetch `ensembl` repository based on the version in `VEP_VERSION`:
```
$ export VEP_VERSION=109.1
$ perl INSTALL.pl --NO_TEST --NO_UPDATE --NO_HTSLIB --NO_BIOPERL -a a
Setting up directories
Downloading required Ensembl API files
- fetching ensembl
curl failed (404), trying to fetch using LWP::Simple
LWP::Simple failed (404), trying to fetch using HTTP::Tiny
ERROR: Failed last resort of using HTTP::Tiny to download https://github.com/Ensembl/ensembl/archive/release/109.1.zip
```
This argument was already deprecated in [release/96](https://github.com/Ensembl/ensembl-vep/commit/9d4684b2b15b535462d89e7ecb35ed2ce7a82d31) and doesn't …
=> Hotfix: remove deprecated VERSION argument from `INSTALL.pl`

modules/Bio/EnsEMBL/VEP/Config.pm, modules/Bio/EnsEMBL/VEP/Constants.pm
https://github.com/Ensembl/ensembl-vep/issues/1357
Solves one of the reason causing test failure - account for non-standard character in dir name when masking them for header.
Test command:
```
vep --force_overwrite -i home/test.this/test.vcf  --assembly GRCh38 --database --db_version 109 
```
Notes:
- The only time it would not add [PATH] replacing the given dir is when we are giving just the file name (e.g. `-i test.vcf`) but that is intended behavior and won't fail test ([test data](https://github.com/Ensembl/ensembl-vep/blob/c5669c88cf93d9b399e680a9c7b6e3774bef25a0/t/VEPTestingConfig.pm#L54) always has some dir path).
- When the dir does not have `/` at the end it will not mask the leaf dir (e.g. `/home/test/test_this` -> `[PATH]/test_this`) which is fine as the intention is to mask …
=> Hotfix: update dir masking pattern in header

modules/Bio/EnsEMBL/VEP/Config.pm, modules/Bio/EnsEMBL/VEP/Parser.pm
After #1361, when running VEP in Docker, we get lots of warnings regarding pre-set environment variables for `INSTALL.pl` that are invalid in VEP:
```bash
$ vep --id rs699 --database --db_version 109 --force
Unknown option: no_update
Ignoring unsupported option 'no_update' found via ENV variable or INI file
Unknown option: no_plugins
Ignoring unsupported option 'no_plugins' found via ENV variable or INI file
Unknown option: pluginsdir
Ignoring unsupported option 'pluginsdir' found via ENV variable or INI file
Unknown option: no_htslib
Ignoring unsupported option 'no_htslib' found via ENV variable or INI file
```
These flags are good to have set up at all times in Docker to abstract users from the internal directory of the Docker image. This PR silently discards invalid options from ENV …
=> Docker fix: silence warnings for invalid options from ENV and INI config

docker/Dockerfile
[ENSVAR-5254](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5254): `Bio::DB::BigFile` installs successfully when assigning the correct `MACHTYPE` based on the platform.
Related with #1304 
Build the Docker image on ARM platform and run a command like:
```
vep --id rs699 --database --db_version 109 --force
```
=> Fix failing `Bio::DB::BigFile` for Docker on ARM platforms

modules/Bio/EnsEMBL/VEP/OutputFactory.pm
For input
`14      56634842        rs10601913      CA      C       209.73  PASS`
hgvs_offset is missing for `NM_017799.4:c.1725-42del` (issue reported here https://github.com/Ensembl/ensembl-vep/issues/1371)
The hgvs_offset for hgvsp is fetched from `$vfoa->hgvs_offset` ([method hgvs_offset](https://github.com/Ensembl/ensembl-variation/blob/release/110/modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm#L1741))
while for hgvsc is `defined($vfoa->{shift_hash}) ? $vfoa->{shift_hash}->{_hgvs_offset} : 0` which returns 0
the issue is probably caused by [this line](https://github.com/Ensembl/ensembl-variation/blob/release/110/modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm#L1366)
This PR updates the way hgvs_offset is fetched for hgvsc.
=> Fix hgvs_offset in OutputFactory 

modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/Dumper/Variation.pm
The default `tmp_dir` in DumpVEP pipeline can be [recursive](https://github.com/Ensembl/ensembl-vep/blob/fc75dcc5534f92d4cf6614ef6c1ad81c2cd01cfb/modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/DumpVEP_conf.pm#L74). It can also be recursive if given as such in cmd argument. 
The pipeline only allows non-recursive dir creation and thus fails if `tmp_dir` not created manually before running the pipeline.
Allow non-recursive `tmp_dir` creation
Tested on cat vep dump - http://guihive.ebi.ac.uk:8080/versions/96/?driver=mysql&username=ensadmin&host=mysql-ens-var-prod-4&port=4694&dbname=snhossain_dump_vep_felis_catus_110&passwd=xxxxx
=> Allow recursive tmp_dir creation in DumpVEP

nextflow/nf_modules/check_VCF.nf, nextflow/nf_modules/merge_VCF.nf, nextflow/nf_modules/split_VCF.nf, nextflow/workflows/run_vep.nf
- Support non-bgzipped files
- Support index files if they exist in the same directory as their VCF files
- Removed sorting in mergeVCF ([ENSVAR-5574](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5574))
- Checks moved to inside the workflow
=> Nextflow: Minor improvements

modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm, t/AnnotationSourceAdaptor.t
Jira: [Card](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5028)
After our team review meeting, it was advised that we need to keep old custom usage. This PR reintegrate old usage, altered in this PR (https://github.com/Ensembl/ensembl-vep/pull/1339)
```sh
--custom filename,test,vcf,exact,0,field1,field2
--custom file=filename,short_name=test,format=vcf,type=exact,coords=0,fields=field1%field2
--custom fields=field1%field2,type=exact,coords=0,file=filename,short_name=test,format=vcf
```
1) Check if old + new usage are working.
=> fix: Get old usage back to VEP custom

modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/CreateDumpJobs.pm
Marc reported failure for dump vep for vertebrates - 
http://guihive.ebi.ac.uk:8080/versions/96/?driver=mysql&username=ensro&host=mysql-ens-hive-prod-1&port=4575&dbname=enseven_dump_vep_vert_110
The `create_dump_jobs` was trying to call `sus_scrofa` regulation database although the job was for `gallus_gallus`. It because that regulation dba already existed from previous job [here](https://github.com/Ensembl/ensembl-vep/blob/fc75dcc5534f92d4cf6614ef6c1ad81c2cd01cfb/modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/CreateDumpJobs.pm#L320).
We need to delete regulation dba just like variation.
http://guihive.ebi.ac.uk:8080/versions/96/?driver=mysql&username=ensadmin&host=mysql-ens-var-prod-4&port=4694&dbname=snhossain_dump_vep_test_110&passwd=xxxxx
=> Fix vep dump for regulation build

nextflow/README.md, nextflow/nf_modules/check_VCF.nf, nextflow/nf_modules/merge_VCF.nf, nextflow/nf_modules/run_vep.nf, nextflow/workflows/run_vep.nf
- Support multiple VEP config files
- Raise error if setting multiple VCF files and VEP config files (currently unsupported)
- Allow to input a Channel of VCF and automatically add tabix index files
- Differentiate output filename to avoid name collisions
- Improve speed when checking bgzip and tabix files
=> Nextflow: Support multiple VEP config files

INSTALL.pl
[ENSVAR-5525](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5525)
Fixes #1364
=> INSTALL.pl: ignore ancestral alleles when downloading all FASTA files

.travis.yml, travisci/harness.sh
Devel::Cover have updated there minimal Perl supported version to v5.12.0 -
https://github.com/pjcj/Devel--Cover/blob/v1.40/Changes (see 1.39 release)
All ensembl-vep travis build will fails on 5.10 coverage test.
- temporarily stopping coverage for perl 5.10
- update trigger-dependency stage to use 5.14 (it was using perl 5.10 before)
=> Stop coverage for perl 5.10

modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/Variation.pm, modules/Bio/EnsEMBL/VEP/OutputFactory.pm
[ENSVAR-5773](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5773)
Update VEP to compare the reference alleles before returning the clinical significance.
This update requires:  https://github.com/Ensembl/ensembl-variation/pull/995
=> Clinical significance - compare ref alleles 

modules/Bio/EnsEMBL/VEP/Constants.pm, modules/Bio/EnsEMBL/VEP/OutputFactory.pm, modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm, modules/Bio/EnsEMBL/VEP/Parser/VEP_input.pm, t/AnnotationSource_File_VCF.t, t/OutputFactory.t, t/OutputFactory_JSON.t, t/OutputFactory_VCF.t, t/OutputFactory_VEP_output.t, t/Parser_VEP_input.t, t/Runner.t
[ENSVAR-3378](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3378) 
The idea is to support indels in VEP default input and to get a minimised allele
`vep --shift_3prime -i input.txt`
3 46358466 46358467 AA/AAG 1
3 46358467 46358467 A/AG 1
3 46358468 46358467 -/G 1
3 46358466 46358466 A/C 1
3 46358470 46358471 TA/GTA 1
=> Support if allele_string is indel in VEP default input

modules/Bio/EnsEMBL/VEP/Parser.pm, modules/Bio/EnsEMBL/VEP/Parser/CAID.pm, modules/Bio/EnsEMBL/VEP/Parser/HGVS.pm, modules/Bio/EnsEMBL/VEP/Parser/ID.pm, modules/Bio/EnsEMBL/VEP/Parser/Region.pm, modules/Bio/EnsEMBL/VEP/Parser/SPDI.pm, modules/Bio/EnsEMBL/VEP/Parser/VCF.pm, modules/Bio/EnsEMBL/VEP/Parser/VEP_input.pm, t/Parser_Region.t, t/Parser_VCF.t, t/Parser_VEP_input.t
[ENSVAR-5226](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5226)
- Validation of each format is now encapsulated in the respective file
- All SO terms are now standardised and available in `Parser.pm` for any input: INS, DEL, TDUP, DUP, CNV, INV, BND (including if encapsulated in `<>`)
- `VEP_input` now accepts the same terms as `VCF`, including `INV`, `BND`, `<CN3>`, `<DEL>`, etc.
- Given the validation restrictions, `Region` accepts most terms, except if encapsulated in `<>` like `<CN0>` and `<INV>`
Does it make sense to accept all SV types in all types of inputs? For instance:
* What does `INS` do if we don't have the inserted sequence in `VEP_input`/`Region`?
* What is the purpose of `CNV` without specifying number of copies?
* `BND` can be specified without mates, but VEP currently …
=> Standardise SV types across inputs: VEP, VCF and Region

modules/Bio/EnsEMBL/VEP/BaseRunner.pm, modules/Bio/EnsEMBL/VEP/BaseVEP.pm, modules/Bio/EnsEMBL/VEP/Config.pm, modules/Bio/EnsEMBL/VEP/Parser.pm, modules/Bio/EnsEMBL/VEP/Runner.pm, t/BaseVEP.t, t/Parser.t, t/Runner.t
[ENSVAR-4683](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4683): report variants skipped and reason (based on user request #1088)
Check also flag documentation in https://github.com/Ensembl/public-plugins/pull/669
* For each line of input file, all variants that are skipped because of parsing issues raise a warning. This warning was improved to also contain the line content.
* Add new argument `--skipped_variants_file` that writes skipped variants to a given file path
* If argument is not provided, the skipped variants file is written
* If file already exists, you will need to use `--force_overwrite` or use another filename
1. Prepare a VCF with malformatted variants:
```
1       2642609 .       G       A
1       2827694 rs2376870       CGTGGATGCGGGGAC C       SVTYPE=DEL;END=2827708
1 …
```
=> Write skipped variants to file

.github/workflows/docker.yml, docker/Dockerfile
Based on issue https://github.com/Ensembl/ensembl-vep/issues/1304 and PR #1367, this PR uses GitHub Actions to run the following actions every time we publish a new release:
1. Build a Docker image for both `linux/amd64` and `linux/arm64` platforms
2. Tag with release version (`release_109.3`, for instance) and `latest`
3. Upload to our DockerHub account
In the settings of our GitHub repo, we will need to set up `DOCKERHUB_USER` and `DOCKERHUB_TOKEN` (the token must include write permissions).
1. Go to a GitHub fork of `ensembl-vep`.
2. Set up `DOCKERHUB_USER` and `DOCKERHUB_TOKEN` based on your personal DockerHub account.
3. Merge this PR changes with the `main` branch of your fork.
4. Create a release with a usual name (`release/110.3`, for instance).
- The GitHub Action will replace …
=> Build Docker image for ARM and x86

modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm, modules/Bio/EnsEMBL/VEP/OutputFactory.pm, t/OutputFactory.t
With https://github.com/Ensembl/ensembl-vep/pull/1317 the `source_name` has been default to `file`. It results in full file path being printed in the output. before the logic was to print only the file name in the output.
Revert back to previous logic.
```
chr2	32198	.	A	G
```
```
vep  --i  <input_file> --assembly GRCh37 --fasta path/to/CHM13.fa --gff path/to/Homo_sapiens-GCA_009914755.4-2022_06-genes.gff3.gz --force --vcf
```
=> Print only file name as gff/gtf source

nextflow/README.md, nextflow/nf_modules/check_VCF.nf, nextflow/nf_modules/generate_splits.nf, nextflow/nf_modules/merge_VCF.nf, nextflow/nf_modules/process_input.nf, nextflow/nf_modules/run_vep.nf, nextflow/nf_modules/split_VCF.nf, nextflow/workflows/run_vep.nf
nextflow-vep many-to-one (and one-to-many) situation with VCF and VEP config file was not working.
This is because giving them as separate channel to `processInputs()` does not work as expected (it is supposed to work like `combine()`). Nextflow handles if one of them is not a channel. 
But going through that route was only considered because of many-to-many situation, and as we are ot supporting that situation I simply used `combine()` which works fine.
**Note** - also stopped channeling `output_dir` through the workflow, it is used only by the `mergeVCF` step. So we can just give input to that step.
=> bugfix: resolve many-to-one situation in nextflow-vep

modules/Bio/EnsEMBL/VEP/BaseVEP.pm, modules/Bio/EnsEMBL/VEP/Parser.pm, modules/Bio/EnsEMBL/VEP/Parser/VCF.pm, t/OutputFactory_VCF.t, t/Parser_VCF.t
[ENSVAR-4587](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4587): `detect_format()` throws an error if the first VCF line contains a malformatted alternative allele based on a (pretty rigid) regex (that is not used for any other lines). This error can be raised even when VEP supports that alternative allele if the regex is not kept up-to-date.
To avoid the error, issues with VCF format should be dealt with on a line-by-line basis. This PR removes the check for the alternative allele and improves checking for issues line-by-line (without using a strict regex).
* [Ignore alternative allele when checking VCF format](https://github.com/Ensembl/ensembl-vep/commit/8e7af98df3ddd735495cc08a9d27851925d6b01f)
* [Support `N` as an alternative allele (used in telomere …
=> Avoid error for alternative allele in first line of VCF input

modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm
Smartmatch is an experimental feature that throws warnings in newer versions of Perl. This PR intends to replace a smart match with an equivalent `if` statement.
=> Avoid smartmatch

docker/Dockerfile
[ENSVAR-5837](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5837)
Reported in - https://github.com/Ensembl/ensembl-vep/issues/1433
Ubuntu 18.04 have come to end-of standard support (see [here](https://wiki.ubuntu.com/Releases)). We are going to update docker image to latest LTS version which is 22.04 and have standard support until April 2027.
- update dependencies from python to python2 (https://github.com/Ensembl/VEP_plugins/pull/620)
- update docs and plugin usage to python2 command
- we also create symlink for python to python2 just in case.
=> Docker: update ubuntu version latest LTS (22.04)

modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm
ENSVAR-5754, fixes #1414 
When a variant is skipped (for instance, for being too large based on `--max_sv_size`), custom annotation is still performed, which can take a long time for big variants. We should not add custom annotation to variants that are marked as skipped.
- Test with multiple variants, some of which should be skipped, while others not, such as:
```
##fileformat=VCFv4.2
##contig=<ID=chr2,length=242193529>
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
##ALT=<ID=DUP:TANDEM,Description="Tandem Duplication">
#CHROM  POS     ID      REF …
```
=> Avoid custom annotation of skipped variants

nextflow/nf_modules/generate_splits.nf, nextflow/workflows/run_vep.nf, t/MultiTestDB.conf
1. If the `output_dir` is a channel current workflows errors out. We need to allow `output_dir` to be a channel in which case we do not do any processing on it (similar to other input arguments).
- renamed `toAbsolute` function to `createOutputChannel` and put the logic for `output_dir` channel there
- renamed `createChannels` to `createInputChannels` to have consistent naming
2. `generate_splits.nf` does not allow 26^2 = 676 splits and not enough for source like dbSNP. Allowing 26^3=17.576 splits which should be enough for any job.
=> nextflow-vep: allow output dir as channel and more splits

modules/Bio/EnsEMBL/VEP/AnnotationSource.pm, modules/Bio/EnsEMBL/VEP/InputBuffer.pm, modules/Bio/EnsEMBL/VEP/OutputFactory.pm, modules/Bio/EnsEMBL/VEP/Parser.pm, modules/Bio/EnsEMBL/VEP/Parser/VCF.pm, t/Parser_VCF.t
ENSVAR-5962: Report consequences for each breakend
- Parse multiple breakends like multiple alternative alleles
- Move breakend parsing code to ensembl-variation: https://github.com/Ensembl/ensembl-variation/pull/1040
- Manta breakends (`CHR2=8;END2=4654454`) are now converted to VCF breakend format (such as `[8:4654454[N`) before being parsed in ensembl-variation
Fixes https://github.com/Ensembl/ensembl-vep/issues/1492
Run multiple types of variants, such as:
```
1       713044  DUP     C       <CN=2>  .       .       END=755966
1       7936271 .       N       N[12:58877476[,N[8:56445865[    .      .      .
1       7936271 .       N       <BND>    CHR2=8;END2= 4654454      .      .
2       227032111    BND00000186    A    [1:106864407[A   .   LowQual …
```
=> Report consequences for each breakend (e112)

modules/Bio/EnsEMBL/VEP/BaseVEP.pm, modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm, modules/Bio/EnsEMBL/VEP/Parser.pm, modules/Bio/EnsEMBL/VEP/Parser/ID.pm, modules/Bio/EnsEMBL/VEP/Parser/VCF.pm, t/Parser_ID.t, t/Runner.t
ENSVAR-5793
Currently, VEP only returns non-structural variants when using variation IDs.
This PR expands the feature to also allow VEP to return SV using their ID[^1].
```
perl vep --id esv1815690  --database --force
perl vep --id esv1850194  --database --force
perl vep --id nsv1000164  --database --force
perl vep --id cnvi0117333 --database --force
perl vep --id CN_571740   --database --force
```
This also works by running `perl vep -i input.txt --database --force`, where the input file contains the identifiers:
```
esv1815690
esv1850194
rs699
nsv1000164
cnvi0117333
CN_571740
```
[^1]: Some SV IDs supported in the Ensembl browser (like [`nsv443016`](http://wp-np2-11.ebi.ac.uk:6070/Sus_scrofa/StructuralVariation/Mappings?r=7:67148496-67211415;sv=nsv443016;svf=665;vdb=variation)) don't …
=> Run VEP with SV IDs

modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm, modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm, modules/Bio/EnsEMBL/VEP/BaseVEP.pm, modules/Bio/EnsEMBL/VEP/Parser.pm, modules/Bio/EnsEMBL/VEP/Parser/VCF.pm
ENSVAR-5610, fixes #1397
- Custom exact matching improvements:
- Avoid matching breakpoints with SNPs when using custom annotation in exact mode
- Only perform this check when using custom annotation in VCF format (other formats do not contain variant type information in a standardised way)
- Bug fix: avoid skipping all subsequent SVs after skipping one
- Improvements to warning messages thrown when skipping variants:
- Warn when skipping any non-supported SV type
- Trim input whitespaces to improve readability of messages
- Bug fix: avoid calling `skipped_variant_msg()` with ensembl-io's parser
- Updates to public documentation: https://github.com/Ensembl/public-plugins/pull/722
Run VEP with custom annotation in exact mode containing breakends and `NON_REF` SVs, such as:
```
1   2642609 …
```
=> Fix custom annotation of breakends and non-supported SVs (exact mode)

modules/Bio/EnsEMBL/VEP/Parser/VCF.pm, t/Parser_VCF.t
Fixes second issue mentioned in #1476: `END` cannot be a smaller number than variant start, according to [VCF 4.4 specifications](https://samtools.github.io/hts-specs/VCFv4.4.pdf), even though this is what happens in the output of breakends from the SV caller Illumina Manta.
As this is a popular SV caller, we will correctly parse the Manta breakend variant (even if out of VCF spec).
* Delete `END` and parse the variant end again (this way, variant end is the same as start)
* Store value of `END` as `END2`
- If the alternative allele of breakend is similar to `[1:106864407[A`, the information in the INFO field is ignored
- Otherwise, if both `CHR2` and `END2` are defined, they will be used to prepare the breakend information (logic already introduced in #1399)
* Remove unnecessary code …
=> Parse END field in Manta breakend variants

modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm, t/AnnotationSource_File_GFF.t, t/AnnotationSource_File_GTF.t
Related with #1506.
Make custom GTF/GFF warnings easier to understand by printing the corresponding filename when skipping features.
Before:
```
WARNING: The feature_type start_codon is being skipped
```
After:
```
WARNING: Ignoring non-supported 'start_codon' feature_type from refseq.gtf.gz
```
You can test with file [t/testdata/custom/refseq.gff.gz](https://github.com/Ensembl/ensembl-vep/blob/release/110/t/testdata/custom/refseq.gff.gz):
```
perl vep --id "NC_000021.9 24993056 . . A" --database --force --gff t/testdata/custom/refseq.gff.gz
```
=> Custom GFF/GTF: add filename to skip `feature_type` warning

modules/Bio/EnsEMBL/VEP/Parser/VCF.pm
This change was introduced in https://github.com/Ensembl/ensembl-vep/pull/1498, but was lost in-between merge conflicts. Everything else seems fine when comparing with `postreleasefix/111` changes.
=> Fix unit tests in main branch

modules/Bio/EnsEMBL/VEP/Config.pm
currently these generate ugly warnings. I use space and comments in the config file for readability
=> ignore blank lines in the config.ini

modules/Bio/EnsEMBL/VEP/Config.pm
Currently, the VEP command-line in output is hiding all plugin parameters preceding a path delimiter (`/` or `\`).
For instance, if we run multiple plugins with a command like:
```
./vep --i $vcf \
--cache homo_sapiens/tabixconverted/ \
--plugin dbNSFP,dbNSFP/4.4a/dbNSFP4.4a_grch38.gz,rs_dbSNP \
--plugin GO,plugin_data/GO_data_files/ \
--plugin DisGeNET,file=DisGeNET/May_2020/all_variant_disease_pmid_associations_final.tsv.gz
```
The output will be:
`## VEP command-line: vep --cache [PATH]/ --input_file [PATH]/A530_small.vcf --offline --output_file [PATH]/vep-output.txt --plugin [PATH]/all_variant_disease_pmid_associations_final.tsv.gz`
- Fix command plugin path hiding parameters for multiple plugins
- [Use lookahead to avoid stripping the directory path if finishing with …
=> Fix plugin path in command line output

cpanfile
DBD::mysql have released new version (5.001) on Oct 4, 2023. This version removes support for MySQL 5 -
https://metacpan.org/dist/DBD-mysql/changes
Hence we need to use lower version than that.
Ensembl repo already have similar PR merged - https://github.com/Ensembl/ensembl/pull/666
=> Restrain using latest DBD::mysql version

docker/Dockerfile
Fixes #1584: Singularity VEP is currently not working because of permission changes to the `/opt/vep` user folder. This PR fixes the folder permissions.
When adding the VEP user, the `/opt/vep` user folder is being created with permissions `750` (`rwxr-w---`) instead of the expected `755` (`rwxr-wr-w`). These permissions come from the file `/etc/adduser.conf` (`DIR_MODE` flag) that was changed in **Ubuntu 22.04**[^1].
[^1]: Previous VEP Docker images based on Ubuntu 18.04 have the correct permissions for the `/opt/vep` user folder.
The solution is simply to change the folder permissions after creating the folder.
Test the Docker image [`nunoagostinho/vep:test3`](https://hub.docker.com/r/nunoagostinho/vep/tags)
=> Fix Singularity: create home dir with expected permissions

modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/Dumper/Variation.pm
[ENSVAR-6087](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6087)
In VEP cache we generally have `pubmed` and `var_synonyms` data from the database. For past couple of release we are getting erratically missing data from them. Note that these two are the only field that are queried from the database and dumped into files and read back again from those dump file when creating the cache.
After adding some debug data (the contents of the dump files read in each job), the cause behind these missing data is found out. We generally keep the data loaded from the dump files in-memory for a species between jobs. But it seems that somehow these objects is persisting jobs between different species and hence one species is getting data from another species.
Simply do not keep in-memory objects. …
=> Avert cross species contamination in VEP cache dump

docker/Dockerfile
In docker/singularity we are seeing the following warning -
```
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
```
This warning originates from linux library `libmysqlclient21` when they rolled out version `8.0.34-0ubuntu0.22.04.1`. Because MYSQL  8.034 deprecates the use of `MYSQL_OPT_RECONNECT` in this version and `DBD::mysql` always sets this flag (to false anyway). See - 
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-34.html#mysqld-8-0-34-deprecation-removal
https://github.com/perl5-dbi/DBD-mysql/issues/354
Ubuntu later released a new library that solves the issue for DBD::mysql `libdbd-mysql-perl`. See -
https://bugs.launchpad.net/ubuntu/+source/mysql-8.0/+bug/2031548
Adding this library removes this unwanted warning.
=> Fix `MYSQL_OPT_RECONNECT` deprecation warning in docker/singularity

modules/Bio/EnsEMBL/VEP/BaseVEP.pm
- [Improvements to `--registry`](https://github.com/Ensembl/ensembl-vep/commit/1a6ac067bd97611e948c92123f9d32c3cbc93937)
- Allow using a relative filename for `--registry`
- Throw error when the registry file is not found
- [Warn when selected `--db_version` is not found in any database names](https://github.com/Ensembl/ensembl-vep/commit/4c7a82539fed2a0789f37d10fa6e737c0f1c5db0)
- Instead of simply returning the warning `MSG: human is not a valid species name (check DB and API version)`, also return a VEP warning stating:
```
WARNING: No database names in ensembldb.ensembl.org:3306 contain version 112
-------------------- WARNING ----------------------
MSG: human is not a valid species name (check DB and API version)
FILE: Bio/EnsEMBL/Registry.pm LINE: 1334
CALLED BY: …
```
=> Improve `--registry` and `--db_version`

modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm, modules/Bio/EnsEMBL/VEP/Stats.pm, t/OutputFactory.t, t/OutputFactory_VCF.t
- [Add table with data version](https://github.com/Ensembl/ensembl-vep/commit/8e21af1a9b6a5641f06da9613cbfda326120f3a4), such as COSMIC, ClinVar, dbSNP and SIFT
- [Fix table layout](https://github.com/Ensembl/ensembl-vep/commit/b3b85c1b2ce8bb9e1916ccc70ceca792a1c015e9)
- [Format paths to files/folders as code](https://github.com/Ensembl/ensembl-vep/commit/960d02212fa7acb80701b8a0e09d04f9042c4747)
- [Fix VEP subversion and show API version in VCF output](https://github.com/Ensembl/ensembl-vep/commit/4c188cc53c07fff6c66a1f01b4f26d71e34bf45e)
- Add VEP subversion to VCF output and summary statistics (before, only the VEP major version was displayed)
- API version is now displayed in the VCF output
Run VEP to return:
- VCF output
- Summary statistics in both HTML and text formats
=> Improve summary stats and VCF output

modules/Bio/EnsEMBL/VEP/BaseVEP.pm
Related to - https://github.com/Ensembl/ensembl-vep/pull/1589
the function `_fetch_chr_synonyms` into a different module but did not get exported
=> Export newly moved function to different module

docker/Dockerfile
Fixes #1590: compile `genesplicer` command for use in VEP Docker/Singularity
This only includes the compiled binary and **not** the associated training data (because of its size). The data still needs to be mounted by the user as usual for a Docker container.
Build the Docker image from this modified Dockerfile and run this command inside Docker:
```
vep --id rs1348242192 --database --force \
--plugin GeneSplicer,/plugins/GeneSplicer/genesplicer,${human_data}
```
https://github.com/Ensembl/VEP_plugins/pull/689: Future improvements to [GeneSplicer.pm](https://github.com/Ensembl/VEP_plugins/blob/main/GeneSplicer.pm) could make this command easier to use.
=> VEP Docker: include GeneSplicer binary

modules/Bio/EnsEMBL/VEP/BaseVEP.pm
Unit tests ([example](https://app.travis-ci.com/github/Ensembl/ensembl-vep/jobs/616556185)) are printing the following line multiple times:
```
Use of uninitialized value $db_version in regexp compilation at /home/travis/build/Ensembl/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 302, <$__ANONIO__> line 139.
```
This PR fixes the issue brought by #1588 
Unit tests should not print the line above no more. For instance, run unit test for `t/BaseVEP.t`
=> Avoid messages of uninitialized value `$db_version` in unit tests

modules/Bio/EnsEMBL/VEP/Parser/Region.pm
Fixes #1617: when inputting short variants in `region` format, VEP prints a warning message:
```
WARNING: line 1 skipped (12:9079672-9079672:C): C type is not supported
```
Also, unknown SV types in `region` format are incorrectly returned with no warning.
This PR does the following:
- Remove the nonsense warning for short variants in `region` format
- Throw warning (and do not return output) when using SVs whose type is not supported
Ensure that running VEP with the following variants works without warnings[^1]:
```
12:9079672-9079672:C
12:9079672-9079672:DUP
12:9079672-9079672:INS:ME
12:9079672-9079672:INS:ME:LINE1
```
Ensure that running VEP with the following variants does not print output (only warnings):
```
12:9079672-9079672:RANDOM
12:9079672-9079672:DELTEST
```
[^1]: The last two …
=> Fix SV warnings for short variants in `region` format

modules/Bio/EnsEMBL/VEP/Stats.pm
This PR fixes two issues with statistics output:
1. When running VEP using only FASTA and GTF with stats enabled, VEP will print the following message:
```
Can't use an undefined value as a HASH reference at /hps/software/users/ensembl/repositories/nuno/ensembl-vep/modules/Bio/EnsEMBL/VEP/Stats.pm line 687.
```
This PR fixes this message by not printing the data version table when there is no such information.
2. Also, when using `--input_data`, the statistics will show (for both HTML and TXT files):
```
Input file	*Bio::EnsEMBL::VEP::Runner::IN
```
This PR will print `--input_data` when `--input_file` is `*Bio::EnsEMBL::VEP::Runner::IN`.
For testing, you can use the FASTA and GTF from the [t/testdata](https://github.com/Ensembl/ensembl-vep/tree/main/t/testdata) folder. The following …
=> Improve statistics output

modules/Bio/EnsEMBL/VEP/Parser.pm, modules/Bio/EnsEMBL/VEP/Parser/VCF.pm, t/Parser_VCF.t
Fixes #1631
When the `SVTYPE` tag is defined and the variant `REF`/`ALT` alleles contain non-`ATCG` IUPAC nucleotide codes (such as `N` and `R` in the user's example), VEP 111 will try to parse the `ALT` allele as a `SVTYPE` and fail:
```
WARNING: line 1 skipped (3 90699772 MantaINS:2:34291:34291:1:0:0 ANNNNN...): ATCACAAATAGGTTCTGAGAATTATTCTGTCTAGTTTTTCTAGCGCCGTTTGAGGCCTATGGTAGAAAAGGGAATATCTTCATAGAAAAACGAGACAGAATAATTCTCAGAACCTATTTGTGATTTGTGCTT type is not supported
```
To avoid this issue, if the `SVTYPE` type is defined and if `ALT` does not resemble one of the [VCF-supported SV types in `ALT`](https://samtools.github.io/hts-specs/VCFv4.4.pdf) (i.e., starting with `INS`, `DEL`, `INV`, `DUP` or `CN`), then the SV type will be based on `SVTYPE` instead of `ALT`.
The warning message was …
=> Fix SVTYPE when using IUPAC nucleotide codes

nextflow/README.md, nextflow/nf_modules/run_vep.nf, nextflow/workflows/run_vep.nf
Added a param `--filters` which takes a string as an argument which can be comma separated list of filter condition. These condition are similar to what we can give in `filter_vep`.
As nextflow-vep can handle only VCF files the `filter_vep` arguments used here is also tailored for VCF file.
```
nextflow -C ${repositories}/ensembl-vep/nextflow/nextflow.config run ${repositories}/ensembl-vep/nextflow/workflows/run_vep.nf \
--vcf $input_file \
--vep_config $vep_config \
--outdir $output_dir \
--output_prefix $output_prefix \
--filters "amino_acids not match X[A-Za-z*]?\/,Feature is ENST00000377918"
```
example variant to check this filter
```
13      57725290        rs1160403026    AGTG    A
```
=> Allow filtering in nextflow-vep

nextflow/README.md, nextflow/nf_modules/check_VCF.nf, nextflow/nf_modules/generate_splits.nf, nextflow/nf_modules/merge_VCF.nf, nextflow/nf_modules/run_vep.nf, nextflow/workflows/run_vep.nf
This PR improves the Nextlow pipeline to run VEP on non-VCF files.
* Replace argument `--vcf` with `--input`
- 8d2b87c50: `--vcf` still supported for backwards compatibility (now prints deprecated message)
* When giving (a folder with) input data to run VEP on:
- Ignore files with specific extensions: `ini`, `registry`, `tbi`, `csi`
- If `vcf` or `vcf.gz` extension, parse using `checkVCF`, `generateSplits` and `splitVCF` (as previously) before running VEP
- If any other extensions, split input files with `splitText` based on `params.bin_size` before running VEP
* In the end, merge split files (as previously)
* 37e4e5b2f: New option `--sort` to sort VCF input/output from VEP (disabled by default)
* 388339075: Remove mentions to deprecated `--skip_check`
* Update documentation
Running the …
=> Nextflow: Accept and split non-VCF input formats

modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm, modules/Bio/EnsEMBL/VEP/OutputFactory/VEP_output.pm, modules/Bio/EnsEMBL/VEP/Utils.pm, t/AnnotationSource_File_VCF.t, t/OutputFactory_JSON.t
[ENSVAR-6276](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6276)
https://github.com/Ensembl/ensembl-vep/issues/1646
When we use `FILTER` field from a VCF file in `--custom` argument, the delimiter for FILTER, which is `;`, is replaced by `,` ([see](https://github.com/Ensembl/ensembl-vep/blob/31a3581b84495b617b2f3980da6c6313ca6d238f/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm#L219)). The reason is `;` have specific meaning in certain file type - for example, in VCF where this `FILTER` is going to put under `INFO`,`;` is used as delimiter to split up different fields in it.
But we also replace any `,` with `&` if found within any specific value under `CSQ` INFO field ([see](https://github.com/Ensembl/ensembl-vep/blob/31a3581b84495b617b2f3980da6c6313ca6d238f/modules/Bio/EnsEMBL/VEP …
=> Update delimiter for FILTER when used for custom option

.travis.yml, travisci/harness.sh
This PR avoids installing Coveralls in Travis CI for the Perl 5.10 job.
~~Also, fixes the `ENV` column in GitHub when running a Travis CI job. Currently showing `One of the secure variables in your .travis.yml has an invalid format.`. Example: https://github.com/Ensembl/ensembl-vep/runs/26175837180~~
=> Avoid installing Coveralls in Travis CI for Perl 5.10

modules/Bio/EnsEMBL/VEP/Parser/VCF.pm
Currently, VEP allows to use VCF input with only the first 5 fields, leaving the remaining 3 mandatory fields as `NULL`.
However, for SVs, VEP tries to do a string comparison on the `INFO` field, resulting in the warnings:
```
Use of uninitialized value in pattern match (m//) at /hps/software/users/ensembl/variation/nuno/ensembl-io/modules/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 340.
Use of uninitialized value in pattern match (m//) at /hps/software/users/ensembl/variation/nuno/ensembl-io/modules/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 359.
Use of uninitialized value in pattern match (m//) at /hps/software/users/ensembl/variation/nuno/ensembl-io/modules/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 378.
Use of uninitialized value in pattern match (m//) at …
```
=> Fix warning when using SV in VCF format with 5 fields

modules/Bio/EnsEMBL/VEP/OutputFactory.pm, modules/Bio/EnsEMBL/VEP/Parser/VCF.pm, t/OutputFactory.t, t/Parser_VCF.t
Issue reported here: https://github.com/Ensembl/ensembl-vep/issues/1703
The option `individual_zyg` uses the following variables:
- `$vf->{hom_ref}->{$ind} = 1`
- `$vf->{non_variant}->{$ind} = 1`
However, these variables are used in other parts of the code as:
`vf->{hom_ref} = 1`
`$vf->{non_variant} = 1`
The solution is to rename the variables.
**Testing**
Input:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  ind
chr1    115258730       .       C       .       .     .    .   GT 0/0
=> Fix option individual_zyg

.travis.yml, cpanfile, docker/Dockerfile
The current Dockerfile for 88.14 contains VEP 90. This is probably because the script to build the Docker image was run after releasing 90, given that the Dockerfile simply retrieves the latest default branch from the repo.
This PR intends to improve the situation by using instructions that more recent VEP Docker builds use, including the possibility of choosing the VEP version to install.
Locally build the image and run VEP with some options to see if it works.
=> VEP 88: Update Dockerfile to build VEP 88.14

modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/CreateDumpJobs.pm
[ENSVAR-6377](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6377)
https://github.com/Ensembl/ensembl-vep/issues/1705
In e110, `assembly_exceptions` table was truncated which contained the sequence region for patches, haploptypes etc. due to changed mechanism of how those regions are showed in Ensembl genome browser.
The VEP cache pipeline depended on the `assembly_exceptions` table to grab those region. This PR aims to fix these issue by updating the current correct way to add non reference sequence regions.
pipeline url - http://guihive.ebi.ac.uk:8080/versions/96/?driver=mysql&username=ensadmin&host=mysql-ens-var-prod-4&port=4694&dbname=snhossain_dump_vep_human_113_test&passwd=xxxxx
=> Fix missing non reference seq region in VEP cache

modules/Bio/EnsEMBL/VEP/CacheDir.pm, modules/Bio/EnsEMBL/VEP/Config.pm
Add new `--full_cache_dir` option to set cache directory directly and check if given directory exists
@nakib103, should we improve the logic to check if the directory is a VEP cache dir? How would we do this?
Run VEP with:
- `--full_cache_dir` with a non-existing directory: should raise error
- `--full_cache_dir` with a VEP cache dir: should work as expected
- `--cache_dir` and `--full_cache_dir` with a VEP cache dir: should ignore `--cache_dir`
- `--cache_dir` as usual: should work as expected
=> Input full path to cache directory

modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/QCDump.pm
Related PR: https://github.com/Ensembl/ensembl-vep/pull/1718
In above PR we updated the pipeline to consider non-reference sequence. We also need to update the QC step so it does not fail.
A pipeline w/t fix:
http://guihive.ebi.ac.uk:8080/versions/96/?driver=mysql&username=ensadmin&host=mysql-ens-var-prod-4&port=4694&dbname=snhossain_dump_vep_human_113&passwd=xxxxx
=> DumpVEP: fix QC step for using non-reference sequence

modules/Bio/EnsEMBL/VEP/Config.pm, modules/Bio/EnsEMBL/VEP/Constants.pm
- Added incompatible flags
- Added warnings for unsupported assemblies
- Style changes in description of header for GENCODE_PRIMARY field
- Consistency with [public-plugins/pull/812](https://github.com/Ensembl/public-plugins/pull/812)
```
vep -i input.vcf --gencode_primary --refseq   # Error 
vep -i input.vcf --gencode_primary --gencode_basic # Error
vep -i input.vcf --gencode_primary --merged # No error
vep -i input.vcf --gencode_primary --assembly GRCh37 # Warning 
vep -i input.vcf --gencode_primary  --flag_gencode_primary --species mus_musculus --assembly GRCm39 # Warning 
```
=> Improving --gencode_primary and --flag_gencode_primary

nextflow/nextflow.config
This PR updates the slurm profile based on testing on our slurm cluster:
* Enable singularity on slurm
* Increase memory limit for VEP (for running without caches)
=> Update slurm profile and resource limits

nextflow/modules/check_VCF.nf, nextflow/workflows/run_vep.nf
In nextflow-vep pipeline we decide on extension of the file and the header content to decide if we go to `runVEPonVCF` process. Added back the extension checking.
=> Check extension also when deciding runVEPonVCF process

modules/Bio/EnsEMBL/VEP/FilterSet.pm
Issue: https://github.com/Ensembl/ensembl-vep/issues/1723
```
filter_vep -i input.vcf --filter "HGNC_ID in HGNC:4836,HGNC:4826" --only_matched 
filter_vep -i input.vcf --filter "HGNC_ID in hgnc.txt" --only_matched 
filter_vep -i input.vcf --filter "HGNC_ID is HGNC:4836" --only_matched 
```
=> Fixing filter when value is hash and contains text and number

docker/Dockerfile
When the branch name to build the Docker image starts with `release/` (release branch), raise an error if there is a mismatch between VEP version and the version in the release branch name.
Check Docker image build completes depending on the branch argument:
- If `ARG BRANCH=main`, it should build successfully
- If `ARG BRANCH=release/113`, it should pass (depending on the VEP version in [modules/Bio/EnsEMBL/VEP/Constants.pm](https://github.com/Ensembl/ensembl-vep/blob/main/modules/Bio/EnsEMBL/VEP/Constants.pm))
- If `ARG BRANCH=release/113.4`, it should pass (subversions are ignored)
- If `ARG BRANCH=release/112`, it should fail
=> Docker: Raise error if VEP version and release branch mismatch

nextflow/README.md, nextflow/nextflow.config, nextflow/workflows/run_vep.nf
- New `--vep_version` parameter allows to specify the VEP version of the image downloaded from Docker Hub
- Add information on downloading VEP cache
- Improve documentation
=> Nextflow: add parameter to specify VEP version

modules/Bio/EnsEMBL/VEP/Runner.pm
ENSVAR-3174
1. Currently, asking for HGVSg using offline and without FASTA, returns HGVSg using `N`s as reference sequence. The correct behaviour would be to mimic what is done with HGVS and error out.
2. When accessing the database to retrieve sequence for HGVSg, a warning should be printed informing the user of such (like done for HGVS).
3. When retrieving sequence from database using `--hgvs`, the message is printed three times:
```
2024-09-03 13:25:00 - INFO: Database will be accessed when using --hgvs
2024-09-03 13:25:00 - INFO: Database will be accessed when using --hgvsc
2024-09-03 13:25:00 - INFO: Database will be accessed when using --hgvsp
```
As `--hgvsc` and `--hgvsp` are internal parameters (not VEP arguments), they should be omitted from the message.
1. `vep --hgvsg …
=> Fix inconsistencies between --hgvs and --hgvsg

modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/RegFeat.pm
https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6436
example variants - 
```
Y 26671671 . A G
Y 17430762 . G T
```
Check database annotation as it changes the database annotation source -
```
vep -i input.txt --database --force --regulatory 
```
It will give no output no output for `--cell_type` parameter (`CELL_TYPE=` in default VEP format)
=> Remove deprecated funcgen function

modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm, modules/Bio/EnsEMBL/VEP/OutputFactory.pm
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2775
Transcript version is always `1` when GFF file is used. It seems it has been hard coded. This PR fixes this issue - 
- try to read version from GFF/GTF file
- if there is no version in the file reports no version even if `--transcript_version` is given.
Test with `rs699` and see if it matches transcript and gene version -
```
vep --id "1 230710048 rs699 A G" --force --gff /pathto/genes.gff3.bgz --fasta /pathto/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --transcript_version --gene_version
```
Check the ticket for GFF and FASTA file location for testing.
=> Parse gene and transcript version from GFF/GTF file

modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm
https://github.com/Ensembl/ensembl-vep/issues/1765
The issue should primarily be fixed by - https://github.com/Ensembl/ensembl-io/pull/171
But this PR add checks for length to be zero and if so set the overlap percentage to be 100%. This can happen for old VCF format where `INFO/SVLEN` is missing and end position is calculated from `INFO/END`.
input.vcf - 
```
2	240692045	.	G	<DEL>	.	PASS	SVLEN=100
```
custom.vcf -
```
2       240692045       nssv211104      G       <DEL>   .       .       DBVARID=nssv211104;SVTYPE=DEL;END=240692045
```
CMD:
```
vep -i input.vcf --force --cache <cache_dir> --offline --cache_version 111 -a GRCh38 --custom file=custom.vcf,short_name=test,fields=DBVARID,num_records=all,reciprocal=1,format=vcf,coords=1,type=overlap,overlap_cutoff=0
```
=> Bugfix: division by zero in overlaps

modules/Bio/EnsEMBL/VEP/Parser/VCF.pm, t/AnnotationSource_File_VCF.t, t/Parser_VCF.t
Depends on https://github.com/Ensembl/ensembl-io/pull/171
We were skipping SV deletion type variant if `start >= end`. The case `start = end` can be a valid case, for example, when SVLEN=1. 
Fixed that check to see if `start > end` or if there is no SVLEN or END information.
The type is `exact` and the custom line is as follows -
```
21	25585735	del2	TG	T	67	SEGDUP;RF
```
So it deletes the G at 25585736 position. Correct way to represent it in SVLEN is with POS=25585736, REF=T (always use the base before polymorphism happens) and SVELN=1 (the difference between ref and alt sequence).
The BND are case affected by the ensembl-io change because it does not have any SVLEN and END. The end here we will  be now `end=start`. Before it was getting `end=start+ref length-1`. END position are not …
=> Downstream changes for get_end fix in VCF parser

modules/Bio/EnsEMBL/VEP/OutputFactory.pm
This update should be included in release/113.
The following warning message: `Transcript-assembly mismatch in ".$hash->{Uploaded_variation}`
should not be printed when the option `--use_given_ref` is on.
The warning indicates there is a mismatch between RefSeq and Ensembl transcripts for the variant stored in `$hash->{Uploaded_variation}`.
=> Fix transcript mismatch warning message

modules/Bio/EnsEMBL/VEP/BaseRunner.pm
When we do not provide `--database` or `--cache` VEP does not setup database connection just like `--offline`. But some part of the code is not aware of this fact and tries to connect to database and fails. 
An example is when VEP is used with `--gff` and `--fasta` and provided with input that contains variant ids which does not work without database. VEP will fail with message - 
```
Can't call method "db" on an undefined value at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/ID.pm line 159, <__ANONIO__> line 1
```
Which is misleading. Also VEP should not try to connect to database in this scenario.
In this PR we force set `--offline` if no database setup is made.
=> Force set --offline if no database setup

modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/Variation.pm, modules/Bio/EnsEMBL/VEP/Config.pm, modules/Bio/EnsEMBL/VEP/Constants.pm, modules/Bio/EnsEMBL/VEP/OutputFactory.pm, modules/Bio/EnsEMBL/VEP/OutputFactory/JSON.pm, modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/Dumper/Variation.pm, t/Runner.t, t/test-genome-DBs/homo_vepiens/variation/meta.txt, t/test-genome-DBs/homo_vepiens/variation/table.sql
Ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5941
Add option to return new clinvar somatic classification.
To test this code, please point to ensembl-variation update: https://github.com/Ensembl/ensembl-variation/pull/1117
=> Add new option to fetch clinvar somatic classification + patch db for 115

modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm
There is a rogue print in custom annotation implementation of ingesting multiple files.
=> Remove redundant print in multi-file custom

modules/Bio/EnsEMBL/VEP/OutputFactory.pm
Reported in https://github.com/Ensembl/ensembl-vep/issues/1867. VEP result mismatch for HGVSg and ClinVar custom annotation when using shift_3prime and not.
We store hgvsg in a hash with allele as a key. This allele is taken from the allele_string of vf - [see](https://github.com/Ensembl/ensembl-variation/blob/ebfce7401437567284b8d6b4e8bbcdb0cc64b898/modules/Bio/EnsEMBL/Variation/VariationFeature.pm#L2039)
But when we try to derive it in VEP OutputFactory we query by allele derived from TranscriptOverlap object - [see](https://github.com/Ensembl/ensembl-vep/blob/a6786e4357f442a81624f58d9e79f343909d717f/modules/Bio/EnsEMBL/VEP/OutputFactory.pm#L1317). 
With shift_hgvs the allele has been shifted. And, with `exact` option VEP will try to do an exact allele match. So it is correct that we …
=> Proper allele matching for fetching HGVSg

nextflow/modules/merge_VCF.nf
When we have input file name with dot nextflow-vep remove all the text after the first dot to create the filename. We only only want to remove the extension.
e.g. - test.vcf.gz --> test.vcf_VEP.vcf.gz
[this PR does not consider if the file is bgzipped or not complications]
Support how client discovers VEP output file in beta site -
https://github.com/Ensembl/ensembl-web-tools-api/blob/main/app/vep/vep_resources.py#L119-L124
Any variant with file name ending with `.vcf` and `.vcf.gz`.
=> nextflow-vep: consider file name containing dot (.)

modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm
Fixed a typo where a hashref field is used before checking existence. Does not cause failure but to avoid getting warning in the output.
**Test**
run `perl t/AnnotationSource_File_VCF.t`
=> Typo: avoid warning for un-initialized string

nextflow/modules/run_vep.nf
Added one patch: 
- During the VEP step, vep passes the vcf via stdout to filter_vep, this errored because VEP was passing containing a header containing a WARNING line at the top, i.e.:
```
WARNING: --gencode_primary option is currently only available for human on the GRCh38 assembly
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
```
- So I patched it to generate one file, then the next, not passing through stdout.
=> Small patches
