Ensembl/ensembl-vep

- INSTALL.pl
- convert_cache.pl
- modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseCacheVariation.pm
- modules/Bio/EnsEMBL/VEP/OutputFactory.pm
- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/Dumper/Regulation.pm
- t/Runner.t
I managed to mess up the commit history on the previous PR, so re-opening with a clean history
> some minor changes (resubmitted)

- modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm
- t/Runner.t
See https://github.com/Ensembl/ensembl-variation/pull/89
> Accompanying test for fix in ensembl-variation

- modules/Bio/EnsEMBL/VEP/Config.pm
- modules/Bio/EnsEMBL/VEP/Constants.pm
- modules/Bio/EnsEMBL/VEP/OutputFactory.pm
- t/OutputFactory.t
- t/Runner.t
- vep
Added ambiguity flag into CL and REST VEP. Changes to ensembl-vep, ensembl-rest and public_plugins have all been made at the same time.
> Added ambiguity flag

- modules/Bio/EnsEMBL/VEP/FilterSet.pm
Fix for https://github.com/Ensembl/ensembl-vep/issues/155
> Allow filtering on HGVS values

- modules/Bio/EnsEMBL/VEP/Constants.pm
- add OverlapBP, OverlapPC to the constants
> add OverlapBP and OverlapPC constants

- modules/Bio/EnsEMBL/VEP/OutputFactory.pm
- t/OutputFactory.t
- Creation of a new filter method for SVs
- Update tests
> New fix for 'pick' options issues for structural variants

- cpanfile
I forgot to add the new dependency required by the G2P plugin. I will create another PR to postreleasefix/94.
> add dependency for G2P plugin

- modules/Bio/EnsEMBL/VEP/Parser.pm
Help with debuging unusual input data
> warn which format has been detected when using verbose

- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/DistributeDumps.pm
Fix to ensure tabix'ed tarball destined for web/REST is not over-written by the non-tabix'ed version.
Also remove REST directory as it is no longer required.
> Cache creation: do not over-write tabixed file with non-tabixed file

- modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/Variation.pm
- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/Dumper/Variation.pm
Clean up allele strings for e!94 and add error catching around allele matching code to report any problem variants.
> Allele string fix

- docker/Dockerfile
- Use less layers by grouping the commands
- Use multi-stage build to reduce layers and final image size
- Try to cleanup the librairies and directories in order to get a
smaller final image (about 30% smaller)
> Rewrite of the Dockerfile:

- .travis.yml
This pull request should not be merged until branch 96 exists on the repositories
> Update travis for release/96

- cpanfile
Add perl module requirement for G2P plugin to cpanfile
> add cpanm requirement for G2P plugin

- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/DumpVEP_conf.pm
Use newly provided bam file supporting MANE set
> update GRCH38 bam file

- README.md
Brief description of JSON output format
> Haplo REST docs

- modules/Bio/EnsEMBL/VEP/Parser.pm
Moving warning message into the right place https://github.com/Ensembl/ensembl-vep/issues/453
> mv waring message

- modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/Variation.pm
Moves check for clinvar source_id to before the variation_feature query
> Fixes rest test failures

- INSTALL.pl
Still sorting out getting the CHECKSUMS file updated on the FTP site, please don't merge until that's sorted
> Updates to installer to support indexed cache files

- modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm
- modules/Bio/EnsEMBL/VEP/Config.pm
- t/AnnotationSourceAdaptor.t
- vep
> Adds flag to prevent assumption of allele specific annotations in custom annotations with comma separated lists

- INSTALL.pl
Related to the issue https://github.com/Ensembl/ensembl-vep/issues/552
> Add an install option to specify the Plugins directory

- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/JoinVEP.pm
Causing a slowdown for production dumps - we'll need to change this for next time - potentially by only having this work for human.
> Revert md5 changes

- modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm
- t/OutputFactory_VCF.t
Linked to https://github.com/Ensembl/ensembl-vep/issues/683
> Skip empty strings in VCF zero check

- modules/Bio/EnsEMBL/VEP/Constants.pm
- modules/Bio/EnsEMBL/VEP/Parser/HGVS.pm
> Prevent lookup of NMs in core db

- .github/ISSUE_TEMPLATE/issue-report.md
I'm adding the template again. I will create another PR against postreleasefix/100
> Create a generic template for the VEP issues

- modules/Bio/EnsEMBL/VEP/Parser/VCF.pm
- t/Parser_VCF.t
Issue #698 
Skip incomplete lines for SV deletion.
> Skip incomplete SV lines

- t/Parser_VCF.t
- t/bam_edit.t
Fix warning messages in test scripts see: ENSVAR-3121
> Fix warnings in VEP test scripts

- modules/Bio/EnsEMBL/VEP/Constants.pm
- modules/Bio/EnsEMBL/VEP/OutputFactory.pm
- t/OutputFactory.t
- vep
I'll submit another PR to 101 when this is approved
> Added shift length flag

- modules/Bio/EnsEMBL/VEP/BaseRunner.pm
- modules/Bio/EnsEMBL/VEP/CacheDir.pm
- modules/Bio/EnsEMBL/VEP/Runner.pm
No test has been added as it would require a grch37 test database to be set up
> Set port to 3337 when assembly is set to grch37

- modules/Bio/EnsEMBL/VEP/OutputFactory/JSON.pm
- modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm
- t/OutputFactory_JSON.t
> Bugfix for --json and --vcf with --shift_3prime

- modules/Bio/EnsEMBL/VEP/Parser/SPDI.pm
- t/Parser_SPDI.t
Not necessary to check if the reference sequence is not genomic.
> SPDI reference sequence

- filter_vep
User request #690 to have an option to flag which variants pass or fail the filter instead of deleting them.
> Add option to filter_vep

- modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/Transcript.pm
Display the correct db_version in cache files 
Related to issue #833
> RefSeq GRCh37 cache 

- .travis.yml
- README.md
- docker/Dockerfile
Version updates only to be done on release branch.
> Release branch updates 103

- modules/Bio/EnsEMBL/VEP/VariantRecoder.pm
- t/VariantRecoder.t
> Update variant recoder by allele 

- modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm
- t/AnnotationSource_File_GFF.t
same as https://github.com/Ensembl/ensembl-vep/pull/870 now for e103
> Fix custom gff missing exons fail -e103

- modules/Bio/EnsEMBL/VEP/OutputFactory.pm
- t/Runner.t
- vep
This flag is being dealt with slightly differently to most in that it wont be included in the documentation as we're not advertising it. Being implemented to help Wormbase
> Support for remove_hgvsp_version

- modules/Bio/EnsEMBL/VEP/Constants.pm
Create new subversion for updating VEP test with alias_to updates.
> increment subversion

- modules/Bio/EnsEMBL/VEP/OutputFactory.pm
Relatively small change. There is no test added currently as were aiming to get this change in before the VM is generated
> Post process var synonyms to control delimiter

- modules/Bio/EnsEMBL/VEP/Constants.pm
- modules/Bio/EnsEMBL/VEP/OutputFactory/JSON.pm
Ticket: ENSVAR-4087
This PR addresses the comments made in https://github.com/Ensembl/ensembl-vep/pull/986
> OutputFactory json - do not convert gene symbol to integer (104)

- modules/Bio/EnsEMBL/VEP/OutputFactory/JSON.pm
Ticket: ENSVAR-4087
Same as #990
> OutputFactory json - do not convert gene symbol to integer (105)

- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/DumpVEP_conf.pm
- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/Dumper/Variation.pm
Fixes ENSVAR-4011
- Updates conf file to point to new queues and data directories
- Removes hard coded tmp_dir reference
- Updates variation dumper to support htslib v2.11
> Updates to vep dump pipeline for codon

- modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/Variation.pm
> Variant Recoder - skip if chr not defined

- modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseCacheVariation.pm
- t/AnnotationSource_Cache_VariationTabix.t
> Fix VEP frequency filtering - match alleles

- .travis.yml
> Updating fungen branch master -> main

- .travis.yml
> Update funcgen branch master to main

- INSTALL.pl
[Ticket ENSVAR-4501](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4501) based on #1067
When running `INSTALL.pl`, this PR allows to display file size in cache data listing:
```
(...)
455 : zosterops_lateralis_melanops_vep_104_ASM128173v1.tar.gz (40 MB)
456 : homo_sapiens_merged_vep_104_GRCh37.tar.gz (16 GB)
457 : homo_sapiens_merged_vep_104_GRCh38.tar.gz (18 GB)
458 : homo_sapiens_refseq_vep_104_GRCh37.tar.gz (14 GB)
459 : homo_sapiens_refseq_vep_104_GRCh38.tar.gz (15 GB)
460 : homo_sapiens_vep_104_GRCh37.tar.gz (14 GB)
461 : homo_sapiens_vep_104_GRCh38.tar.gz (15 GB)
 
Total: 165 GB for all 461 files
 
?
```
When displaying the predefined list of species (e.g. after running `INSTALL.pl -u not_a_valid_URL`), the list will not show the file size. However, it will show the total number of …
> Preview cache download size

- .travis.yml
[ENSVAR-4782](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4782)
> Corrected funcgen branch in .travis.yml 

- .travis.yml
[ENSVAR-4782](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4782)
> Corrected funcgen branch in .travis.yml

- modules/Bio/EnsEMBL/VEP/Parser.pm
[ENSVAR-3734](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3734)
#883
> Fixing warning message

- .travis.yml
Renaming master to main for files dependent on ensembl-variation repo
> Renaming master to main for ensembl-variation

- modules/Bio/EnsEMBL/VEP/Parser.pm
- t/Parser.t
[ENSVAR-4844](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4844)
#1178
> Check ref bug

- .gitignore
- modules/Bio/EnsEMBL/VEP/Stats.pm
Moving fix to post release branch per PR request. Addresses issue with graph x-axis sorting and sorting of charts on page.
Issue (https://github.com/Ensembl/ensembl-vep/issues/1001).
Link: [JIRA](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4244)
> Issue 1001 - statistics/graph sorting

- modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm
[ENSVAR-4484](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4484)
This PR attempts to fix the pattern matching for MT transcripts
> Annotation of MT transcripts in RefSeq

- modules/Bio/EnsEMBL/VEP/OutputFactory/JSON.pm
- t/OutputFactory_JSON.t
[ENSVAR-4993](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4993)
This PR attempts to replace `looks_like_number` with regex to account for the pattern pos/len
> Parsing pos/len in json with --total_length argument

- modules/Bio/EnsEMBL/VEP/Parser.pm
[ENSVAR-4844](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4844)
#1243
> Changes to the check ref

- modules/Bio/EnsEMBL/VEP/Parser.pm
Cherry-picking the commit from PR: https://github.com/Ensembl/ensembl-vep/pull/1244 to release/107
> Check_ref update to release/107

- variant_recoder
[ENSVAR-4364](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4364)
> Variant recoder MANE select only available for human

- modules/Bio/EnsEMBL/VEP/VariantRecoder.pm
- t/VariantRecoder.t
Input to test: `ENSP00000355627.5:p.Met259Thr` 
[ENSVAR-4842](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4842)
> Variant Recoder add missing synonyms

- modules/Bio/EnsEMBL/VEP/Parser/VCF.pm
Fix unit test from last CN alteration PR. Travis wasn't running.
1) Just let travis run;
> hotfix: CN alteration broken test

- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/QCDump.pm
[ENSVAR-5311](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5311)
> VEP cache: Add a check for empty file

- modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm
- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/DumpVEP_conf.pm
Jira: [Card](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5288)
More information in JIRA.
Just make sure file was downloaded to correct folder.
> feat: Update GRCh38 dump BAM file

- .travis.yml
- README.md
- docker/Dockerfile
Add Travis + Dockerfile + README necessary alterations.
Example last release: https://github.com/Ensembl/ensembl-vep/pull/1261
None
> fix: Add travis + Dockerfile + README conf updates

- modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm
- modules/Bio/EnsEMBL/VEP/Config.pm
- t/AnnotationSourceAdaptor.t
- t/Config.t
- t/OutputFactory.t
- t/OutputFactory_JSON.t
- t/OutputFactory_Tab.t
- t/OutputFactory_VCF.t
- t/OutputFactory_VEP_output.t
This PR is a remerging of PR (https://github.com/Ensembl/ensembl-vep/pull/1317) without conflicts.
1) Just run last PR tests.
> feat: non-ordered custom refactor conflict remerge

- t/OutputFactory.t
https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3733
> Update ranking of feature elongation and truncation consequences

- .travis.yml
- t/OutputFactory_Tab.t
- t/OutputFactory_VCF.t
- t/OutputFactory_VEP_output.t
Fixes test for docker which add more parameters in the vep command from environment variables
> Fix test for docker

- docker/Dockerfile
- t/OutputFactory_Tab.t
- t/OutputFactory_VCF.t
- t/OutputFactory_VEP_output.t
- Fix headers added by docker ENV variables
- Add branch to Dockerfile stage 2
> Fix docker tests

- INSTALL.pl
> Hotfix: Accept FTP links (mimic PR #1303)

- modules/Bio/EnsEMBL/VEP/Config.pm
- t/OutputFactory_Tab.t
- t/OutputFactory_VCF.t
- t/OutputFactory_VEP_output.t
- loosen up header test because we are now reading from ENV variables
- fix STDERR redirection
> Fix test failures

- modules/Bio/EnsEMBL/VEP/Parser/HGVS.pm
[ENSVAR-2603](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2603)
* This PR sets the default region size limit for HGVSg to `--max_sv_size` instead of the hardcoded 5kb limit.
* This also means that the default region size limit for HGVSg has increased from 5kb to 10Mb.
* Note: a HGVSg with a deletion around 10Mb takes ~1m30s to process.
* This PR requires changes from https://github.com/Ensembl/ensembl-variation/pull/985.
**Testing**
1. You can use the following HGVSg identifiers to test the limit with `--max_sv_size`:
```
16:g.89820416_89883065del
16:g.89818265_89883065del
16:g.79883066_89883065del
16:g.79818265_89883065del
NC_012920.1:m.1_10000000del
```
2. For HGVSg cases where the region limit goes above the limit, a warning message is printed:
```
WARNING: Unable to parse HGVS …
```
> Use `--max_sv_size` as the HGVSg region limit

- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/BaseVEP.pm
- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/DistributeDumps.pm
- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/JoinVEP.pm
- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/QCDump.pm
[ENSVAR-5386](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5386)
Test pipeline:
http://guihive.ebi.ac.uk:8080/versions/96/?driver=mysql&username=ensadmin&host=mysql-ens-var-prod-4&port=4694&dbname=snhossain_dump_vep_test_109&passwd=xxxxx
bacteria test pipeline -
http://guihive.ebi.ac.uk:8080/versions/96/?driver=mysql&username=ensadmin&host=mysql-ens-var-prod-4&port=4694&dbname=snhossain_dump_vep_test_55&passwd=xxxxx
Need to update production docs - https://www.ebi.ac.uk/seqdb/confluence/display/GTI/Data+dumping#Datadumping-AddfrequenciestoGVFandVCFdumps%E2%80%93humanonly(runthispipelineafterVEPdumpsvert)
> Update dump VEP directories

- .github/workflows/docker.yml
* Fix repository of Docker image
* Allow manual run to build Docker images
* Add tag when manually creating Docker image
> Fix Docker build process

- modules/Bio/EnsEMBL/VEP/Constants.pm
Hotfix 110.1: Update VEP subversion (from 110.0 to 110.1)
> Hotfix: subversion update

- modules/Bio/EnsEMBL/VEP/Config.pm
- modules/Bio/EnsEMBL/VEP/Constants.pm
- modules/Bio/EnsEMBL/VEP/OutputFactory.pm
- modules/Bio/EnsEMBL/VEP/Parser/VCF.pm
- t/Config.t
- t/Haplo_Runner.t
- t/OutputFactory.t
- t/Parser_VCF.t
- t/Runner.t
This PR replaces https://github.com/Ensembl/ensembl-vep/pull/1474
[ENSVAR-4523](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4523)
This option is similar to --individual 
Add option to public docs: https://github.com/Ensembl/public-plugins/pull/726
> Add new option --individual_zyg

- modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/Variation.pm
- modules/Bio/EnsEMBL/VEP/OutputFactory.pm
Revert https://github.com/Ensembl/ensembl-vep/pull/1423
> Clinical significance - remove clinvar ref allele check 

- modules/Bio/EnsEMBL/VEP/OutputFactory.pm
Issue reported here: https://github.com/Ensembl/ensembl-vep/issues/1520
Ticket: [ENSVAR-6071](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6071)
> --hgvsg_use_accession to fetch chromosome synonyms from cache in offline mode

- modules/Bio/EnsEMBL/VEP/Constants.pm
> Updating VEP version

- .travis.yml
- README.md
- docker/Dockerfile
Updating travis/readme and docker to 112
> Updates for release/112 branch

- modules/Bio/EnsEMBL/VEP/OutputFactory/BaseTab.pm
- modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm
> Deterministic order for software versions in header

- modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm
A bit more descriptive warning.
> Update WARNING for un-supported feature type from GFF/GTF file

- t/OutputFactory.t
change related to https://github.com/Ensembl/ensembl-variation/pull/1042
> Fix unit test regarding HGVS dup lookup update

- t/AnnotationSource_File_GTF.t
Fixes unit tests related with https://github.com/Ensembl/ensembl-io/pull/156
> Remove problematic unit test

- t/AnnotationSource_File_GTF.t
> [!IMPORTANT]
> This PR needs to be merged **after** https://github.com/Ensembl/ensembl-vep/pull/1625
Fixes unit tests related with https://github.com/Ensembl/ensembl-io/pull/156
> Fix unit test for e113

- modules/Bio/EnsEMBL/VEP/Config.pm
- modules/Bio/EnsEMBL/VEP/FilterSet.pm
Add missing incompatible options. See https://github.com/Ensembl/ensembl-variation/pull/1074
> Fix incompatibility

- t/test-genome-DBs/homo_vepiens/core/meta.txt
- t/test-genome-DBs/homo_vepiens/core/table.sql
- t/test-genome-DBs/homo_vepiens/funcgen/meta.txt
- t/test-genome-DBs/homo_vepiens/funcgen/table.sql
- t/test-genome-DBs/homo_vepiens/otherfeatures/meta.txt
- t/test-genome-DBs/homo_vepiens/otherfeatures/table.sql
- t/test-genome-DBs/homo_vepiens/variation/meta.txt
- t/test-genome-DBs/homo_vepiens/variation/table.sql
- t/test-genome-DBs/homo_vepiens_coreonly/core/meta.txt
- t/test-genome-DBs/homo_vepiens_coreonly/core/table.sql
- t/test-genome-DBs/multi/ontology/meta.txt
- t/test-genome-DBs/multi/ontology/table.sql
- t/test-genome-DBs/mus_muscuvep/core/meta.txt
- t/test-genome-DBs/mus_muscuvep/core/table.sql
> Patching test databases

- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/DumpVEP_conf.pm
[ENSVAR-6277](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6277)
> Add slurm configuration for DumpVEP pipeline

- modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm
Fixes #1695
Some RefSeq transcripts are being incorrectly filtered out by the strict regex in use based on their `stable_id`.
Currently, the following `stable_id` are available from RefSeq transcripts:
<details>
<summary>Script to print transcript's `stable_id` from cache</summary>
You can use the following script to get the transcript's `stable_id`:
```perl
#!/usr/bin/env perl
use strict;
use warnings;
use Data::Dumper;
use Storable qw(nstore_fd fd_retrieve);
foreach my $f(@ARGV){
open my $fh, "gzip -dc $f |" or throw("ERROR: $!");
my $obj = fd_retrieve($fh);
print $_->{stable_id}, "\n" for @{$obj->{MT}};
}
```
</details>
```
ATP6
ATP8
COX1
COX2
COX3
CYTB
ND1
ND2
ND3
ND4
ND4L
ND5
ND6
RNR1
RNR2
TRNA
TRNC
TRND
TRNE
TRNF
TRNG
TRNH
TRNI
TRNK
TRNL1
TRNL2
TRNM
TRNN
TRNP
TRNQ
TRNR
TRNS1
TRNS2 …
```
> Fix filtering of RefSeq transcripts in mitochondria

- modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/RegFeat.pm
[ENSVAR-6367](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6367)
> Skip adding EMER regulatory feature in VEP cache

- .github/workflows/docker.yml
Add workflow to automatically create Docker
> VEP 88 Docker: Create docker.yml worfklow

- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/Dumper/Core.pm
Test pipeline: http://guihive.ebi.ac.uk:8080/versions/96/?driver=mysql&username=ensadmin&host=mysql-ens-var-prod-4&port=4694&dbname=snhossain_dump_vep_human_113_test&passwd=xxxxx
> Include gencode primary in transcript attrib list for dumper pipeline

- modules/Bio/EnsEMBL/VEP/OutputFactory.pm
Ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4493
This PR is related to https://github.com/Ensembl/ensembl-variation/pull/1103
Add to release/113
> Transcript-assembly mismatch refseq annotation - print warning

- t/Parser_VCF.t
Additional unittest fixes related to https://github.com/Ensembl/ensembl-vep/pull/1773
> Fix tests for get_end

- INSTALL.pl
Ticket: [ENSVAR-6628](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6628)
> Remove dependency on non indexed cache

- modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/Variation.pm
- modules/Bio/EnsEMBL/VEP/OutputFactory.pm
- modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/Dumper/Variation.pm
Ticket: [ENSVAR-5773](https://embl.atlassian.net/browse/ENSVAR-5773)
ClinVar was updated to store the variant ref allele in `phenotype_feature_attrib`: https://github.com/Ensembl/ensembl-variation/pull/1168
The variation API was updated to use the ref allele: https://github.com/Ensembl/ensembl-variation/pull/1169
> Update VEP to process clinvar ref allele

- INSTALL.pl
- docker/Dockerfile
[ENSVAR-6839](https://embl.atlassian.net/browse/ENSVAR-6839)
Build a docker container and check if LoF plugin is not installed by default
> Optionally skip plugins during installation
